### ISSUE TITLE
Integrate with Travis CI

### ISSUE THREAD

**Issue by filfreire** [XProger/OpenLara#101]
* Integrate with [travis-ci.org](https://travis-ci.org) and create a `.travis.yml` file
* Add Travis badge to README.md

/cc @XProger

**Comment by XProger** [comment]
@filfreire https://travis-ci.com/plans why do I need it?

**Comment by filfreire** [comment]
@XProger you don't need the paid version, you can use the open-source free version, similarly to [OpenTomb project](https://travis-ci.org/opentomb/OpenTomb).

**Comment by XProger** [comment]
ok, how it can help me?

**Comment by filfreire** [comment]
@XProger it's a tool to help the project's maintainability, useful for you, contributors and newcomers alike.

Every time you make a new commit to the master branch or someone contributes a PR, Travis attempts to build OpenLara. 

You know beforehand if merging a given PR will cause the build to fail and you can easily keep track of the build's state.

It's also a step forward to have the "how to build" (like I mentioned on issue #100 ) information standardized and anyone can jump in and contribute "more easily" to the project.

**Comment by filfreire** [comment]
@XProger if you allow, I can help you tackle issue #100 and then this issue.

**Comment by XProger** [comment]
about Travis CI, I suppose it's useless for this project, would be better to have cross-platform alternative.

**Comment by Gh0stBlade** [comment]
Apppveyor is probably better for cross platform custom build scripts and deployments.

**Comment by filfreire** [comment]
@XProger would you consider we follow-up on this issue with an issue to integrate with Appveyor?

/cc @Gh0stBlade

**Comment by XProger** [comment]
@filfreire no, Appveyor is the same shit, sorry.
