### ISSUE TITLE
Water is black in the Lara Croft House [Opera]

### ISSUE THREAD

**Issue by atomic83GitHub** [XProger/OpenLara#104]
***What is the issue?***

The water in the Lara Croft House is black with the Opera web browser, I use a intel+AMD configuration.
Nvidia seems better but still have broken light effect into the water itself.

Here is a picture of the issue:
![capture](https://user-images.githubusercontent.com/26351275/35775557-269e0620-098b-11e8-9a3f-a4a8fe034301.PNG)

***Note:***
The game is not compatible with Opera Turbo causing broken background in the main menu and in loading screen.

**Comment by atomic83GitHub** [comment]
Also I forget to mention that the game seems pretty slow on the Opera browser, is this related?

**Comment by XProger** [comment]
@atomic83GitHub check it in Chrome or Firefox please on this hardware.

**Comment by atomic83GitHub** [comment]
Tested with Firefox, Internet explorer 11 and edge, all are fine as you can see:

![capture](https://user-images.githubusercontent.com/26351275/35781262-24082e7e-09e8-11e8-89cf-ae5da3c731cd.PNG)

**Comment by XProger** [comment]
@atomic83GitHub great, so it's not hardware problem, I'll check in Opera.

**Comment by XProger** [comment]
works in Opera 58.0.3135.47
