### ISSUE TITLE
Engine should accept TITLE.PHD file

### ISSUE THREAD

**Issue by benneti** [XProger/OpenLara#105]
These are the files in my level/1 directory:
`CRED1.PCX  CUT1.PHD  CUT4.PHD     GYM.PHD       LEVEL10B.PHD  LEVEL2.PHD   LEVEL4.PHD  LEVEL7A.PHD  LEVEL8B.PHD  TITLEH.PCX
CRED2.PCX  CUT2.PHD  EIDOSPC.PCX  INSTALL.PCX   LEVEL10C.PHD  LEVEL3A.PHD  LEVEL5.PHD  LEVEL7B.PHD  LEVEL8C.PHD  TITLE.PHD
CRED3.PCX  CUT3.PHD  END.PCX      LEVEL10A.PHD  LEVEL1.PHD    LEVEL3B.PHD  LEVEL6.PHD  LEVEL8A.PHD  readme.txt`
but OpenLara won't start unless I rename TITLE.PHD to TITLE.PSX, is this intended?
(Also it then fails when I choose a level, I think maybe it would work if i rename all files)

Thank you for your work on this project :)

**Comment by XProger** [comment]
"level/1/TITLE.PSX" used as default, I'll add checking for TITLE.PHD. But there is another way, you can just copy OpenLara.exe into folder of PSX, PC or unpacked obb android version of original game, then OL can automatically recognize content platform and version 8)

**Comment by benneti** [comment]
Thanks, thats nice to know 👍
