### ISSUE TITLE
Newest version does not compile anymore under linux

### ISSUE THREAD

**Issue by benneti** [XProger/OpenLara#106]
`clang-7.0: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang-7.0: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
../../libs/minimp3/minimp3.cpp:878:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register int tmp;
    ^~~~~~~~~
../../libs/minimp3/minimp3.cpp:2003:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register int16_t *synth_buf;
    ^~~~~~~~~
../../libs/minimp3/minimp3.cpp:2004:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register const int16_t *w, *w2, *p;
    ^~~~~~~~~
../../libs/minimp3/minimp3.cpp:2004:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register const int16_t *w, *w2, *p;
    ^~~~~~~~~
../../libs/minimp3/minimp3.cpp:2004:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register const int16_t *w, *w2, *p;
    ^~~~~~~~~
5 warnings generated.
/tmp/stb_vorbis-0ac1fb.o: In function 'sincos(float, float*, float*)':
stb_vorbis.c:(.text._Z6sincosfPfS_+0x0): multiple definition of 'sincos(float, float*, float*)'
/tmp/main-a08499.o:main.cpp:(.text._Z6sincosfPfS_+0x0): first defined here
clang-7.0: error: linker command failed with exit code 1 (use -v to see invocation)`

I tried to fix it but I did not find a sincos function in main.c and am not to versed in c++.

**Comment by XProger** [comment]
#37a162e
