### ISSUE TITLE
cannot run under linux

### ISSUE THREAD

**Issue by giucleand** [XProger/OpenLara#109]
Excellent work, thank you for your continuous effort.  I must say. I'm speechless. Yet, I seem to be unable to run the game for quite some time (more than 6 months) under Linux (ChaletOS, Ubuntu variant of 14.04).

I get this when trying to run:

a@a-CELSIUS-W280:~/struct/t/OpenLara-master/bin$ ./OpenLara 
error loading file "level/1/TITLE.PSX"
Vendor   : Intel Open Source Technology Center
Renderer : Mesa DRI Intel(R) Ironlake Desktop 
Version  : 2.1 Mesa 10.1.3
cache    : /home/a/.OpenLara/
supports :
  variyngs count : 16
  binary shaders : true
  vertex arrays  : true
  depth texture  : true
  shadow sampler : true
  discard frame  : false
  NPOT textures  : true
  RG   textures  : true
  border color   : true
  anisotropic    : 16
  float textures : float = full, half = full

shader: cache warm up...
shader: compile COMPOSE -> MIRROR 
! shader: 0:506(1): error: syntax error, unexpected '*'

! program: error: linking with uncompiled shader
shader: compile COMPOSE -> ROOM 
shader: compile COMPOSE -> ROOM alphaTest 
shader: compile COMPOSE -> ROOM underwater 
shader: compile COMPOSE -> ROOM underwater alphaTest 
shader: compile COMPOSE -> ENTITY 
shader: compile COMPOSE -> ENTITY underwater 
shader: compile COMPOSE -> ENTITY alphaTest 
shader: compile COMPOSE -> SPRITE alphaTest 
shader: compile COMPOSE -> SPRITE underwater alphaTest 
shader: compile COMPOSE -> FLASH 
shader: compile COMPOSE -> FLASH alphaTest 
shader: compile COMPOSE -> MIRROR clipPlane
! shader: 0:507(1): error: syntax error, unexpected '*'

! program: error: linking with uncompiled shader
shader: compile COMPOSE -> ROOM clipPlane
shader: compile COMPOSE -> ROOM alphaTest clipPlane
shader: compile COMPOSE -> ROOM underwater clipPlane
shader: compile COMPOSE -> ROOM underwater alphaTest clipPlane
shader: compile COMPOSE -> ENTITY clipPlane
shader: compile COMPOSE -> ENTITY underwater clipPlane
shader: compile COMPOSE -> ENTITY alphaTest clipPlane
shader: compile COMPOSE -> SPRITE alphaTest clipPlane
shader: compile COMPOSE -> SPRITE underwater alphaTest clipPlane
shader: compile COMPOSE -> FLASH clipPlane
shader: compile COMPOSE -> FLASH alphaTest clipPlane
shader: compile AMBIENT -> ROOM 
shader: compile AMBIENT -> ROOM alphaTest 
shader: compile AMBIENT -> ROOM underwater 
shader: compile AMBIENT -> ROOM underwater alphaTest 
shader: compile AMBIENT -> SPRITE alphaTest 
shader: compile SHADOW -> ENTITY 
shader: compile WATER -> MASK 
shader: compile WATER -> STEP 
shader: compile WATER -> CAUSTICS 
shader: compile WATER -> COMPOSE 
shader: compile WATER -> DROP 
shader: compile FILTER -> DEFAULT 
shader: compile FILTER -> DOWNSAMPLE 
shader: compile FILTER -> GRAYSCALE 
shader: compile FILTER -> BLUR 
shader: compile FILTER -> MIXER 
shader: compile GUI -> DEFAULT 
shader: cache is ready
Segmentation fault

**Comment by XProger** [comment]
please check with latest code or latest release build https://github.com/XProger/OpenLara/releases/tag/20180226

**Comment by giucleand** [comment]
Thank you! They both work now.
