### ISSUE TITLE
firefox 58.0.2 problem 

### ISSUE THREAD

**Issue by codz01** [XProger/OpenLara#111]
Hi , just failed to run on firefox 58.0.2 
![ol](https://user-images.githubusercontent.com/10813427/37246936-a264329c-2467-11e8-8267-a4747d900e6c.png)

**Comment by XProger** [comment]
Game can't be run in FireFox private mode just because in this case your browser blocks indexed database used for downloaded data cache. Sorry.

**Comment by codz01** [comment]
oh thnanks for the info , seems tracking protection is enabled by default in firefox ,thus , it wont be easy to fix for newbie users
