### ISSUE TITLE
Joystick button mapping

### ISSUE THREAD

**Issue by pablomaiolo** [XProger/OpenLara#113]
I've noticed that the buttons in the joystick options belong to an XBox gamepad. I have a PS2 style gamepad and the SELECT button has the same number as the jkNone button defined in platform/nix/main.cpp, so it doesn't work for me.

I think it would be a good idea to use a mapping file to take into account different button distributions, or map every gamepad into an ideal model like RetroArch does with the RetroPad.

**Comment by jclc** [comment]
Using a Dualshock 4 on Firefox, I can't seem to be able to remap anything to the d-pad. Pressing the right stick is also interpreted as d-up for some reason.

**Comment by XProger** [comment]
check your gamepad mapping here http://html5gamepad.com/

**Comment by XProger** [comment]
tested my DS4 on Firefox, looks like it doesn't fully support DS4, so I can't do anything

**Comment by XProger** [comment]
![image](https://user-images.githubusercontent.com/796763/51987319-48c31080-24b3-11e9-9de1-68fb56c68514.png)
chrome vs firefox
