### ISSUE TITLE
Firefox crash issue

### ISSUE THREAD

**Issue by atomic83GitHub** [XProger/OpenLara#114]
When you play OpenLara for the first time on the firefox browser, enter in the Lara house will result in a Javascript exception. This can be worked around by cleaning the navigator cache and restarting the browser.

Tested on 2 PC, the same error happen on booth of them.

**Comment by XProger** [comment]
OpenLara was run earlier on these PC's?

**Comment by atomic83GitHub** [comment]
Yes. And by the way here is the exception:

![image](https://user-images.githubusercontent.com/26351275/38373563-d82db224-38f1-11e8-9042-c85a79ac7b04.png)

**Comment by XProger** [comment]
I suppose it was fixed by cd2778adcfc307ecca47157042c15d778b9a23d3
