### ISSUE TITLE
Assertion failed - St. Francis' Folly/Colosseum

### ISSUE THREAD

**Issue by Gh0stBlade** [XProger/OpenLara#118]
LEVEL4 (St. Francis' Folly)
Room: 5
This assertion is hit in room 5 causing the game to stop working. 
https://github.com/XProger/OpenLara/blob/master/src/cache.h#L920

**Comment by Gh0stBlade** [comment]
LEVEL6 (Colosseum)
Room: 4
This assertion is hit in room 5 causing the game to stop working.
https://github.com/XProger/OpenLara/blob/master/src/cache.h#L920

**Comment by XProger** [comment]
ground/underwater enemies doesn't update their zone indices >_<

**Comment by Gh0stBlade** [comment]
Ah I see, also occurs on Palace Midas room 54.
