### ISSUE TITLE
City of Khamoon Crash

### ISSUE THREAD

**Issue by Gh0stBlade** [XProger/OpenLara#119]
LEVEL8A
Room: 36
Happening on: 36b7355084c3f4294a9915d48b74572ddb97a176

Getting a crash here: https://github.com/XProger/OpenLara/blob/master/src/enemy.h#L408

`Exception thrown: read access violation.
Character::getZones(...) was 0xBE8F4D4.`

**Comment by XProger** [comment]
fixed
