### ISSUE TITLE
Menus (Title/Inventory) soft lock (Win32).

### ISSUE THREAD

**Issue by Gh0stBlade** [XProger/OpenLara#122]
Tested with: 36b7355084c3f4294a9915d48b74572ddb97a176

Looks like there is a bug with the sound platform code for Windows causing low FPS. If you wait in the title menu or inventory the framerate will slowly decrease until the game freezes. Commenting out line https://github.com/XProger/OpenLara/blob/master/src/platform/win/main.cpp#L546 does resolve the framerate drop.

I tested this in Debug mode so the framerate is generally lower. It may not be noticeable in release builds.

**Comment by XProger** [comment]
fixed cd2778adcfc307ecca47157042c15d778b9a23d3
