### ISSUE TITLE
Atlantis Laura Doppelganger death trigger bug, Level Unplayable 

### ISSUE THREAD

**Issue by andrewsyc** [XProger/OpenLara#125]
Used to work fine but for some reason Doppelganger disappears and doesn't trigger the room exit door to open. Video posted below. 

# Image is Clickable to YouTube Video demonstrating problem. 

[![IMAGE ALT TEXT HERE](https://i.imgur.com/bSqZWIM.png)](http://www.youtube.com/watch?v=psiQ9pExGg0)

**Comment by andrewsyc** [comment]
I think you fixed this or it mostly works now.

**Comment by XProger** [comment]
fixed b59c8bfb6e32ea53c4f2d26721690394f8120abd
