### ISSUE TITLE
FMV

### ISSUE THREAD

**Issue by XProger** [XProger/OpenLara#129]
- [x] TR1 PC (Escape 124 + PCM 8)
- [x] TR2 PC (Escape 130 + PCM 16)
- [x] TR3 PC (Escape 130 + IMA ADPCM)
- [x] TR PSX (STR + XA ADPCM)
- [ ] TR SAT (CPK)
- [ ] research for web solution (mp4?)

**Comment by TeslaRus** [comment]
bik?

**Comment by Gh0stBlade** [comment]
Bik is part of radgametools which is closed source/needs a license to use if my memory is correct.

**Comment by Lwmte** [comment]
Bik is used only in TR4-5, which is a very far-off for OL...

**Comment by vanfanel** [comment]
@XProger : I extracted the PSX FMVs using ISOBUSTER in RAW mode (2352 files of sector data) and still I get some sparse white noise periods on intro video and a segfault before it ends. Is that supposed to be like this with current sources?

**Comment by XProger** [comment]
@vanfanel use https://github.com/m35/jpsxdec for this, I'll check isobuster

**Comment by vanfanel** [comment]
@XProger : Thanks, but that program causes an "out of bounds" exception when opening the image. This is the JRE I am using on my GNU/Linux machine:
```

manuel@vader:~/Downloads/lara$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.17.10.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

```

Isobuster seems to work fine, but as I said, among resulting files the game intro seems to be showing audio and video problems.

**Comment by BF3000** [comment]
One suggestion.
If due to licensing reason is impossible to implement original video-audio support, maybe it is easier to add support for popular&open video and audio codecs, and add some strict folder& file name order, so it can play properly.
LIke mp4&Theora for video, ogg,opus,flac for audio.

**Comment by Gialel** [comment]
Could someone please tell me if it is possible to play the first Tomb Raider from 1996 with Open Lara with flac audio and MP4 or avi video?

**Comment by XProger** [comment]
Nope

**Comment by Gialel** [comment]
I understood, thanks.

**Comment by Gialel** [comment]
I understood, thanks.
