### ISSUE TITLE
Documentation for compiling or provide executables

### ISSUE THREAD

**Issue by TheIndra55** [XProger/OpenLara#136]
I'm running into some issues while compiling OpenLara on Windows using the Visual Studio project, so i was wondering if there was any documentation to compiling OpenLars, i also remember earlier there were OpenLara executables in the git repo but looks like they got removed. Is it possible to release these executables again or as i said release a little documentation on compiling like dependencies etc.

**Comment by XProger** [comment]
what problems?

**Comment by XProger** [comment]
Windows SDK doesn't contain glext.h, so [download](https://www.khronos.org/registry/OpenGL/api/GL/glext.h) it and copy to SDKs GL folder.

**Comment by TheIndra55** [comment]
Than you i will try after i installed Windows SDK, right now i'm running into problems while installing Windows SDK
