### ISSUE TITLE
Jump and grab does not grab (edit: at 60 Hz)

### ISSUE THREAD

**Issue by pgimeno** [XProger/OpenLara#143]
To reproduce, go to Lara's mansion (TR1) and follow the instructions in ledge 2 of the gym.

Expected effect: The edge is grabbed.

Actual effect: Lara falls to the floor.

Important to reproduce: walk up to the border from behind, don't jump backwards from below (because if she's closer than the walk limit, she won't fall)

**Comment by XProger** [comment]
can't reproduce

**Comment by pgimeno** [comment]
I've noticed it depends on the frame rate. It works fine with vsync off. With vsync on, it's reproducible in my system with a framerate of 60 Hz, but not with a framerate of 75 Hz.
