### ISSUE TITLE
Vr version runs on Galaxy S7? Possibility for Oculus Rift?

### ISSUE THREAD

**Issue by Midnightmaster** [XProger/OpenLara#147]
Does this work with the Samsung Galaxy S7? Unpacked the "main.40.com.squareenix.tombraider1classic.obb" file and copied it to my SD card:
https://imgur.com/a/MFEOg2I
Unfortunately, the program crashes immediately when I start it.

Is it possible to run OpenLara on OpenVR or rather Oculus Rift? That would be really cool!
Thank you!

**Comment by XProger** [comment]
should work, this is internal storage?

**Comment by Midnightmaster** [comment]
Nevermind, i´m an idiot! Internal ist right, runs! Thank´s for the quick response!
