### ISSUE TITLE
Support for VR on Windows

### ISSUE THREAD

**Issue by mrhatkat** [XProger/OpenLara#149]
Hello,
I noticed that the source files make use of OpenVR for presumably the GoogleVR version you showed on the YouTube channel. Does the windows build also support OpenVR functionality  or does it need to be built separately? If it needs to be built separately, what are the steps to building it?
#100
Also, would you like another hand at adding additional functionality with OpenVR?

**Comment by XProger** [comment]
Early versions has OpenVR support, but now it doesn't work. So it in my plan, but first I need to experiment with hands aiming (IK and controllers tracking) and movement (hmd tracking).

**Comment by mrhatkat** [comment]
I'd like to help with the OpenVr support. I've worked with the library a little bit in the past. In which files are you implementing the logic for it?

**Comment by mrhatkat** [comment]
Could you point me to the files that have the OpenVr code implemented? I want to mess around with it and see if I can get it in a more working state.

**Comment by XProger** [comment]
win/main.cpp
level.h / renderGame

**Comment by mrhatkat** [comment]
Thanks, I'll take a look at that.

**Comment by mrhatkat** [comment]
I managed to get the VR working. It looks very good by the way. The only major problem I've run into is that in first person mode, you aren't able to rotate right or left.
