### ISSUE TITLE
Can't find GYM.PHD when run in Debug Mode on Visual Studio

### ISSUE THREAD

**Issue by mrhatkat** [XProger/OpenLara#150]
The game runs fine when I click the OpenLara.exe, but there seems to be a problem when run in visual studio debug.

"Error loading file GYM.PHD"

I think the problem might be how the "contentDir" variable is defined here,since it never seems to be set.
(utils.h,1326)
``` 
if (contentDir[0] && (!cacheDir[0] || !strstr(name, cacheDir))) {
            char path[255];
            path[0] = 0;
            strcat(path, contentDir);
            strcat(path, name);
            f = fopen(path, "rb");
        } else
            f = fopen(name, "rb");

        if (!f) {
            #ifdef _OS_WEB
                if (name) {
                    this->name = new char[strlen(name) + 1];
                    strcpy(this->name, name);
                }
                osDownload(this);
            #else
                LOG("error loading file \"%s\"\n", name);
                if (callback) {
                    callback(NULL, userData);
                    delete this;
                } else {
                    ASSERT(false);
                }
            #endif
```
and another source of the problem might be
(gameflow.h,754)
`if (Stream::existsContent("DATA/GYM.PHD") || Stream::existsContent("GYM.PHD"))`

since the actual directory the files are under is `level/1/GYM.PHD` unless we are no longer using this style of formatting

**Comment by XProger** [comment]
set working directory in the project settings
