### ISSUE TITLE
Problems on Switch

### ISSUE THREAD

**Issue by szczuru** [XProger/OpenLara#151]
Hi, i ave few problems on my switch using latest build.
I'm using files from GOG version (+ogg soundtrack)

-How can i get main menu background to show in TR1? I've copied all files from data dir to level\1\ dir
-Is there any way to run TR 2 or 3? I've copied all necessary files to level\2 (and 3), fmv\2 (and 3) and audio...

This propably isn't implemented but... is there any way to look around using right stick when holding "look" button (instead of left stick).

**Comment by XProger** [comment]
check readme.txt, remove all data from /switch/OpenLara/, extract archive there (OpenLara.nro and OpenLara.nacp), then copy game content from your original CD there (TR1, TR2, TR3 whatever) and play.
