### ISSUE TITLE
Video in 16:9 Fullscreen

### ISSUE THREAD

**Issue by GPIforGit** [XProger/OpenLara#155]
Since nearly all videos (except the core-logo-video) are 4:3 with really big blank space top and bottom, it woulde be nice, when the videos can be optional zoomed in. Simple strech the video to the window-width, center and cut top and bottom.
Maybe this is also a good solution for the loading and title screens.

**Comment by XProger** [comment]
acceptable only for PSX FMVs, because they have black fields right in the video frames >_<
