### ISSUE TITLE
TR1_PSX - Colloseum - missing Celling

### ISSUE THREAD

**Issue by GPIforGit** [XProger/OpenLara#157]
i know, the original TR has here a black sky too, but maybe it would be a good idea to replace it with a brown sky:
Like here: Picture before and after:
https://imgur.com/a/ppKzFHa

**Comment by XProger** [comment]
maybe like this https://youtu.be/4DqJOv-wmuU ? :)

**Comment by GPIforGit** [comment]
Looks great.

Funny thing. I don't know why, but for me the Colloseum was allways in the underground, not in the surface with a sky. That's why I suggested a brown/sandy celling.

btw, I commiled the latest commit (add sky shader) and I have still a black sky in the lost valley... - maybe because i used the PSX-data?

**Comment by XProger** [comment]
clouds shader isn't commited yet, need to be optimized :)

**Comment by GPIforGit** [comment]
Maybe a night-sky would be also nice. Since the old TR use a Black Sky it would feel more like the original Tomb Raider. The lost valley look complete diffrent on "day settings".

**Comment by XProger** [comment]
![image](https://user-images.githubusercontent.com/796763/52181319-81d7e980-2801-11e9-8094-d09f16a6f930.png)

**Comment by XProger** [comment]
![image](https://user-images.githubusercontent.com/796763/52947620-4ce29f80-3388-11e9-9b3b-aa3507f9bdd4.png)
![image](https://user-images.githubusercontent.com/796763/52947627-510ebd00-3388-11e9-9d59-a3a92c8b3a4c.png)
