### ISSUE TITLE
TR3_PSX - Missing soundtrack

### ISSUE THREAD

**Issue by GPIforGit** [XProger/OpenLara#159]
The soundtrack of the TR3 is stored in the XA-Files, it can be extract with jpsxdec_v0-99-7_rev3397 to .wav.
You geht many files from F1.XA[0].wav,F1.XA[1].wav .... F16.XA[0].wav.
The order is identical with the PC-Version F1[0] is Track 002, F1[1] is 003 and so on. Only two important things:
Track 079, 080, 081 doesn't exist. The "excelent"-voice-Track F11.XA[0] is 082 (and not 079)
Track 122 and 123 are identical - the secret-Sound F16.XA[0]

I renamed the files to 002 to 123 and do some changes in the sourcecode:

gameflow.h
function "getGameTrack":
```

if (useEasyStart) {
...
                case VER_TR3_PSX :
					// GPI
					sprintf(title, "%03d", track);
					if (!checkTrack("", title) && !checkTrack("audio/3/", title) && !checkTrack("audio/", title)) {
						callback(Sound::openCDAudioWAD("audio/cdaudio.wad", track), userData);
						return;
					}
					break;
					// GPI end
                default : return;
....
                case VER_TR3_PSX :
					//GPI
					sprintf(title, "audio/3/%03d.ogg", track);
					if (Stream::existsContent(title))
						break;
					//GPI END
                    #ifndef _OS_WEB
                        callback(Sound::openCDAudioWAD("audio/3/cdaudio.wad", track), userData);
                        return;
                    #else
                        sprintf(title, "audio/3/track_%02d.wav", track);
                    #endif
                    break;
                default : return;


```
Now the Soundtrack is playing. But it seems, that the oggs, that i created, are playing too fast. Start "Laras home" and the voice of lara is too high pitched...

btw.  it seems that here are many defekt transparent-colors in the textures.
https://imgur.com/a/ItLWqm3

And the first level isn't really playable. Lara start sliding the ramp down and then hang in the geometry.

**Comment by XProger** [comment]
PC version also has no 79-81 tracks with identical 122 and 123. Original XA has 37.8 kHz, so you should convert it into 44.1 kHz for normal speed.

In my research of TR3 PSX format I can't find transparency flag for textures or faces, I will be back to this problem soon :)

TR3 added new floor, ceiling and portal types and I should rewrite big part of OL code to support this, but TR2 at first.
