### ISSUE TITLE
Frame limiter

### ISSUE THREAD

**Issue by TheIndra55** [XProger/OpenLara#160]
Is/could there be a possibility to lock FPS on 60 while playing? As it now runs constantly on 1000 FPS which my laptop doesn't really like

I tried looking for it but couldn't find any issues about this, a commandline parameter would be great or ingame setting.

**Comment by XProger** [comment]
turn on VSync in the detail settings and if it doesn't work in the your video driver settings

**Comment by TheIndra55** [comment]
Couldn't find the option in Nvidia settings on Linux, but i guess that's a "me" problem. This can be closed i guess
