### ISSUE TITLE
Analog Control

### ISSUE THREAD

**Issue by GPIforGit** [XProger/OpenLara#163]
The original TR is designed for digital control, but it would be nice to use the left/right Stick a little bit more.

For example left stick: 0-30% Deadzone, 31-65% walking, 66-100% running.
Only problem is, that it is easy to accidently walk when the player wants to run. And the animation is really slow.
I have two suggestions for this problem:
1) When an analog introduced walk can be disturbed by a "analog" running. But this would break the animations and maybe the position of the player.
2) Walking becomes a delay, maybe something like 32ms (2 frames on 60 fps). 

click the left stick could also toogle running/walking

for the right stick could be used to look around without pressing the look button. It should be used in a "absolut" mode. which means, when i press the right stick 50% to the right, Lara should look "50%" of the possible head-movment to the left.
Or the right-stick does moves lara too, but only with walking.

**Comment by XProger** [comment]
check official android version, he did the similar control scheme and it was very uncomfortable, so no
