### ISSUE TITLE
ITLEJAP not defined

### ISSUE THREAD

**Issue by CoolAbhi1290** [XProger/OpenLara#181]
When ever I start up the game, the variable "ITLEJAP" is not defined and an exception gets forced hence stopping the game for good.

![Screenshot 2019-04-24 at 5 41 39 PM](https://user-images.githubusercontent.com/43380238/56698641-40e0ca00-66b8-11e9-960b-bffcc6854de5.png)
@XProger

Device: Chromebook
OS update: Up-To-Date
Previously script running: True
Caught errors: None
Affecting other devices: Unknown

**Comment by XProger** [comment]
I don't have Chromebook to check this and I don't know what ITLEJAP means ) Looks like TITLEJAP but for TR2 and TR3 web version using TITLEUS.PNG and TITLEUK.PNG

**Comment by CoolAbhi1290** [comment]
> I don't have Chromebook to check this and I don't know what ITLEJAP means ) Looks like TITLEJAP but for TR2 and TR3 web versions use TITLEUS.PNG and TITLEUK.PNG

My best guess what ITLEJAP is would be a browser cookie missing value, which in this case was undefined which stopped the game from recovering the progress in the game. All I had to do was delete the cookies in my browser and refresh the page :)

**Comment by CoolAbhi1290** [comment]
> I don't have Chromebook to check this and I don't know what ITLEJAP means ) Looks like TITLEJAP but for TR2 and TR3 web versions use TITLEUS.PNG and TITLEUK.PNG
