### ISSUE TITLE
Lara going headless in Lara's House (Looks funny!)

### ISSUE THREAD

**Issue by CoolAbhi1290** [XProger/OpenLara#182]
Look at this image -

![Screenshot 2019-04-25 at 5 22 46 PM](https://user-images.githubusercontent.com/43380238/56772229-f413f680-677e-11e9-8529-4056f4af8b7e.png)

When I go to the doorway and click "camera button" + "action button" to go to first person mode, she goes headless.

This is how you might fix it. She goes headless because when the camera goes to her head, her head interferes and obstructs the camera's view. So to fix that, you might want to make a variable for _If locked camera is true_, and then you would check if the camera is locked into and position and the user requests first person mode, deny it. An easy peasy line of code must do the job...

Possible label(s): Render, Logic

Device: Chromebook
Glitch found on other devices: true
Glitch existed before: true
Glitch is major: true
Visual glitch: true
Core glitch: false
Code bug: false
Additional override needed: true
Fixable: true

Found by @CoolAbhi1290 (that's me)
To @XProger  (the developer)

**Comment by XProger** [comment]
found by all who plays OL, can't be fixed with current camera triggers system. Because camera isn't fixed at moment or render call, but trigger on the floor successfully switching camera to fixed state every frame on update routine... I suppose, original game checks previous fixed camera index for this type of triggers, and didn't switch it back if it's the same as last one. But I'm not sure with this.
It's perfectly works when camera is really fixed by timer or something :)

**Comment by CoolAbhi1290** [comment]
> Was found by all who plays OL, can't be fixed with current camera triggers system. Because camera isn't fixed at moment of render call, but trigger on the floor successfully switching camera to fixed state every frame on update routine... I suppose, original game checks previous fixed camera index for this type of triggers, and doesn't switch it back if it's the same as last one. But I'm not sure with this.
> It's perfectly works when camera is really fixed by timer or something :)

I found this glitch happening in all devices, ranging from phones to VR to PCs.

**Comment by XProger** [comment]
yep, do you have good ones? Me too ;)

**Comment by CoolAbhi1290** [comment]
> yep, do you have good ones? Me too ;)
> I'm currently working on data export / import to standard 3D format (glTF), so I hope someone sometime can make HD mod by using this feature.
> I welcome any suggestions everywhere :)

I can make full HD images for you... So now, there are going to be 120p, 480p, 720p, 1080p sprites, right?

**Comment by XProger** [comment]
Every level use own tile set with textures (256x256 * 13 tiles), OL pack all into atlases like [this](http://xproger.info/projects/OpenLara/shots/atlas_packing.png)

**Comment by CoolAbhi1290** [comment]
> Every level use own tile set with textures (256x256 * 13 tiles), OL packs all into atlases in runtime like [this](http://xproger.info/projects/OpenLara/shots/atlas_packing.png) and it might be different for each level.

Ok, on it. The new textures will be ready in about a week or two. If you like it, please use it, and if not, well do whatever you like... I will be very happy to contribute to this awesome project :)

**Comment by XProger** [comment]
[Here](http://xproger.info/tmp/Tomb_Raider_HiRez_android.zip) is lazy HD port from official Anroid and iOS versions.

**Comment by CoolAbhi1290** [comment]
> [Here](http://xproger.info/tmp/Tomb_Raider_HiRez_android.zip) is lazy HD port from official Android and iOS versions.
> And how it looks like in OpenLara (from my old tests)
> ![image](https://user-images.githubusercontent.com/796763/56777006-d030cf00-67d7-11e9-86b2-4602314a4597.png)

Looks amazing! And to be honest, this is turning from a bug report to something totally different! Here is the [link](https://1drv.ms/u/s!AhOlktr0MshokS_3F6Bw6HZW7nKe?e=h5qx84) to the place you can visit all the versions of the new textures. Before I start working on this, I have a few questions...
Does this support svg (vector) images?

**Comment by XProger** [comment]
before you starts check other HD texture packs [here](http://www.tombraiderxtra.com/downloads.php)
only raster images supported

**Comment by CoolAbhi1290** [comment]
> before you starts check other HD texture packs [here](http://www.tombraiderxtra.com/downloads.php)
> only raster images supported

Ok, only raster. Other textures are great, but there are details here and there which need work... OMG, is this getting official?

**Comment by CoolAbhi1290** [comment]
> before you starts check other HD texture packs [here](http://www.tombraiderxtra.com/downloads.php)
> only raster images supported

Where do I find your games? And how do I test the new textures?

**Comment by XProger** [comment]
There is no way to test it now in OpenLara, but you can find original TombATI version (see link above) and test with it

**Comment by CoolAbhi1290** [comment]
> There is no way to test it now in OpenLara, but you can find original TombATI version (see link above) and test with it

How do you like the new textures coming? Link to project [here](https://1drv.ms/u/s!AhOlktr0MshokS_3F6Bw6HZW7nKe?e=G9xEhp).

**Comment by XProger** [comment]
use TombATI textures pack at link above as ref

**Comment by CoolAbhi1290** [comment]
Looking back to 2 years ago, boy did I have no clue how GitHub worked. Very nicely handeled.
