### ISSUE TITLE
Invisible Pierre  "damages" Lara

### ISSUE THREAD

**Issue by Cramer-0xbit** [XProger/OpenLara#185]
In St Francis Folly after the 1st encounter with Pierre

[![PIERRE BUG VIDEO](https://cdn-b-east.streamable.com/image/8gcdr.jpg?token=OWoDd6fP5MGcqPlyS0RUyw&expires=1558200420)](https://streamable.com/s/8gcdr/ggbitq)

**Comment by lemmi23** [comment]
It happened a few time to me also. I noticed it in areas where human ennemies are.
It looks like Lara get hurt in somes specific locations, like this.
![TR1-invisible-hurt](https://user-images.githubusercontent.com/50141823/57141217-06fb7c00-6dba-11e9-8b8d-956404cf27ba.gif)

I reported it a few days ago : https://github.com/XProger/OpenLara/issues/183
