### ISSUE TITLE
Web version http://xproger.info/projects/OpenLara/ - does jumping not work?

### ISSUE THREAD

**Issue by JonasT** [XProger/OpenLara#186]
I tried the usual ALT key to jump, both in Chromium and Mozilla Firefox on a Linux machine, but couldn't make it work. In firefox ALT toggles the browser menu when windowed and does nothing in fullscreen, in chromium there is no visible action in neither windowed nor fullscreen. No jumping, sadly.

The game also just says "jump button" in Lara's dialogue, so it would be nice if there was a short listing of the controls below the 3d canvas so one can peek at them before going into fullscreen! (because is it even ALT? I'm not sure, that is what I remembered from years ago but it has been a while)

This project is extremely impressive and if not for the lack of a jump button, I probably would have played a level or two right there on the spot *right in the web browser* because omg that is amazing!

**Comment by XProger** [comment]
![image](https://user-images.githubusercontent.com/796763/58219515-e452e800-7d13-11e9-95ed-a0cb9faefccd.png)
