### ISSUE TITLE
Raspberry Pi Version

### ISSUE THREAD

**Issue by symbios24** [XProger/OpenLara#188]
Hello there,i have a raspberry pi 3 and upon running of openlara i got a segmentation error or memory corruption error  and the games does not run at all after that

any help?

**Comment by XProger** [comment]
works only after reboot rpi?

**Comment by symbios24** [comment]
i copied all the files with the executable in the same folder  it does not work after reboot upon running it loads the shaders after that it stops with that error i cannot fild any log

**Comment by symbios24** [comment]
is there a specific way to put the original files or i just put them in the folder like this

**Comment by symbios24** [comment]
what i mean is i made a folder with name tomb and put inside the original folder data and the openlara executable do i have to put the executable inside the folder data?

**Comment by XProger** [comment]
in my case for PSX version it looks like this
![image](https://user-images.githubusercontent.com/796763/58710368-d1e84680-83c4-11e9-9efb-975639b6f165.png)
can you start executable from the console and check logs?

**Comment by symbios24** [comment]
it worked i rename the folder data to tomb and put inside openlara

does it work with tomb raider 2 and 3?

**Comment by XProger** [comment]
OpenLara can open TR2 & TR3 levels and FMVs, but not playable

**Comment by symbios24** [comment]
does it plays tomb raider 2 and 3? what is not playable the videos?

**Comment by XProger** [comment]
not playable game series, new weapons, states, objects and enemies are not implemented for now
