### ISSUE TITLE
Stack corruption.

### ISSUE THREAD

**Issue by Gh0stBlade** [XProger/OpenLara#19]
File: Format.h
Based on: 7f004415e1ffe829a43b9203d76fec4ab0c5b6a7
Issue: struct "FloorInfo" declared at line beginning 709 specifies the maximum amount of trigger commands "trigCmd[16]". This constant however is not sufficient enough for certain levels resulting in writing to out of bound memory. As a result the stack is corrupted. This noticeably occurs in LEVEL4.PHD (St. Francis' Folly) Damocles key room, if you stand on the sector where the key is laid.
"info.trigCmd[info.trigCmdCount++] = trigCmd;" on line 1043 is where the out of bound writing occurs when info.trigCmdCount++ > 16.

I would suggest replacing the constant with a higher value and adding an assertion.

Cheers.

**Comment by cochrane** [comment]
I'm wondering whether a std::vector might be a best choice here. It seems like the FloorInfo objects are constructed quite frequently, so maybe it's too expensive, but my gut feeling is that the simpler code would outweigh any negative effects.
