### ISSUE TITLE
Some Enemies have no AI

### ISSUE THREAD

**Issue by mailmartinviljoen** [XProger/OpenLara#198]
Not that I mind but some enemies do not have AI. I loaded TR2 PSX from title.psx. First level The tiger is running around, but further spiders simply fall down to the floor and do not move. further along the way where there is a pool below the castle wall and another tiger that is also seems to have AI as its running around. If I remember correctly on the castle wall same scene where the pool and tiger is there is supposed to be birds. I guess they were spawned and not moving from where they originate.

I also loaded another level and the enemies "Humans" don't move  you also cannot kill them.

Is it possible to make lara jump much higher ? Certain places on the map will then be explorable. :-)

**Comment by ABelliqueux** [comment]
Hi, 

> Not that I mind but some enemies do not have AI

If I 'm not mistaken, Xproger is now focusing on getting the first Tomb Raider fully working ( AI, physics, etc. ) and focus on TR2 will come later . This is reflected in the "Roadmap" section of the project's presentation, ie "OpenLara 2". Thus, physics and AI for TR2/3/4 are not implemented yet .

> Is it possible to make lara jump much higher ? 

In OpenLara, there is a DOZY mode, whatever that means. It allows you to ['fly/swim'](https://www.youtube.com/watch?v=3XRhF8STEtI) even when not in water. You can then access all the map thoroughly. For the moment the combination for entering this mode is Look + Duck + Action + Jump

**Comment by mailmartinviljoen** [comment]
Thank you very much, DOZY mode sounds interesting. Will give it a go.
