### ISSUE TITLE
Pressing P or O makes Lara swim anywhere she wants

### ISSUE THREAD

**Issue by Qix-** [XProger/OpenLara#204]
Not sure if this is an outdated bug but on the web demo, while in the level, pressing O lets Lara swim anywhere (including up to the ceiling, etc.) and P teleports her to some pool (I've never played the game before so I don't know where it's at).

EDIT: [Here is what happens with O](https://i.imgur.com/rn3UUai.gifv) and [here is what happens with P](https://i.imgur.com/w8V6gCX.mp4).

**Comment by XProger** [comment]
O is hot key for DOZY cheat mode; P teleports to some areas on sone levels for debug purposes
