### ISSUE TITLE
[Switch] Recompile to make compatible with 9.0.0

### ISSUE THREAD

**Issue by cucholix** [XProger/OpenLara#205]
Apps needs to be recompiled against the new libnx or else they won’t be able to detect button inputs, atmosphere will still give support for old libnx, but eventually it will be dropped in the future.

More info: https://github.com/Atmosphere-NX/Atmosphere/releases

**Comment by XProger** [comment]
yep, I saw this in release notes, new version will be released soon. Thanks.

**Comment by XProger** [comment]
done
