### ISSUE TITLE
Overlapping rooms bug

### ISSUE THREAD

**Issue by vvs-** [XProger/OpenLara#214]
This old bug is still present and in the same place. OT is ridden with the same type of bugs. I think there are bugs that just can't be fixed reliably without consulting decompiled code (or Core's source code).
![Screenshot from 2019-09-23 23-00-05](https://user-images.githubusercontent.com/5171934/65458977-849e5200-de57-11e9-87ba-81bd9c6e1885.png)

**Comment by XProger** [comment]
I plan to use stencil buffer to fix this

**Comment by vvs-** [comment]
I doubt this could be a solution. TeslaRus used the same approach but there are lots of different cases, e.g. in TR UB, TR3 and TR5.

**Comment by vvs-** [comment]
@Gh0stBlade could you please tell if you are planning on decompiling line of sight functions any time soon? This could be a solution.

**Comment by Gh0stBlade** [comment]
If i recall correctly its nothing to do with line of sight (los) code. GetRoomBoundsASM is the function in TR5 PSX that builds a list of rooms for drawing.

**Comment by vvs-** [comment]
Probably I misunderstood what @stohrendorf said a few years ago. Anyway, I'm really disappointed in previous attempts to solve this problem and believe that decompilation is the only right solution.

**Comment by Gh0stBlade** [comment]
GetRoomBoundsASM(camera.pos.room_number);//Original game code call in TR5 (builds list of rooms)

See this monstrosity:
https://github.com/TOMB5/TOMB5/blob/20f0b96d4b1edc5b92355121b9c1f7d9594ff20f/SPEC_PSXPC_N/MATHS.C#L771

For PSX it heavily relies on the GTE but it can be stripped out of course.

**Comment by tommadams** [comment]
I used a [different approach](https://github.com/tommadams/jsraider/blob/99713f231588b828ac42bc2b9c523d5f2f7b96f1/renderer.ts#L222) to fix this issue.

If a room potentially overlaps another: before rending the room, draw all its portals to the stencil buffer using a unique value. Then when rendering the room, set the stencil test to reject all pixels that don't have that value in the stencil buffer.

For this to work, you have to sort the rooms by depth before rendering them, and disable the stencil test if the camera's near plane intersects one of the portals. It's robust enough to work for all the TR1 levels I've tested and I haven't seen issues with any geometry being incorrectly clipped.
