### ISSUE TITLE
Classic water and waterfall textures are not animated

### ISSUE THREAD

**Issue by vvs-** [XProger/OpenLara#215]
Of course, if there are water shaders enabled then there are no water textures at all. But waterfalls are still present in that case.

**Comment by XProger** [comment]
did you see any solution for this?

**Comment by vvs-** [comment]
Of course, it always worked in OT. While not everything made it back to TRS this one was documented from the beginning: https://opentomb.github.io/TRosettaStone3/trosettastone.html#_animated_textures_2

**Comment by XProger** [comment]
ah, thanks, for some reason I skipped animated textures section while implementing TR4 format support
https://github.com/XProger/OpenLara/blob/master/src/format.h#L6208
