### ISSUE TITLE
objects & triggers

### ISSUE THREAD

**Issue by XProger** [XProger/OpenLara#22]
- [x] change soundtrack by trigger (fade in / fade out)
- [x] trigger masks
- [x] trigger once flag
- [x] boulders
- [x] spikes
- [x] pendulum blades
- [x] underwater current
- [x] lava particles
- [x] Shooting darts (Caves) [hit collision check]
- [x] Collapsible floor (Caves)
- [x] Collapsing ceiling (Tomb of Qualopec)
- [x] Lightning (St. Francis' Folly)
- [x] Thor's hammer (St. Francis' Folly)
- [x] Falling swords (St. Francis' Folly)
- [x] Hand of Midas (Palace Midas)
- [x] Fire Traps (Palace Midas)
- [x] Clamping Metal Doors (The Cistern)
- [x] Lava (levels in Atlanta)
- [x] centaur statue
- [x] save game crystal

**Comment by rr-** [comment]
Following traps are missing from the list:

- Abyss (I don't think there was any place with this)
- Shooting darts (Caves)
- Collapsible floor (Caves)
- Collapsing ceiling (Tomb of Qualopec)
- Lightning (St. Francis' Folly)
- Thor's hammer (St. Francis' Folly)
- Falling swords (St. Francis' Folly)
- Hand of Midas (Palace Midas)
- Fire Traps (Palace Midas)
- Clamping Metal Doors (The Cistern)
- Lava (levels in Atlanta)
