### ISSUE TITLE
Running Tomb Raider 2 and later versions on my new PC

### ISSUE THREAD

**Issue by Laramazone** [XProger/OpenLara#229]
Dear XProger,

First of all I want to thank you so much for making it possible to play Lara again! I am 42 years old and have not played PC many games in my life except Lara, back then in the 90s. :) When I found your website I was very happy as the new PCs (laptops) come without CD drive and thus I cannot install all my old games. 
So playing TR1 was great fun and of course now I wish to continue with TR2. Now there is a strange problem which I did not have with TR1 and I hope you can help me with. (I am a total IT ignorant and I will just try to do all the steps you recommend).

1. When I chose the first level of TR2 all seemed normal at first. But Lara cannot climb. She can grip and pull up, but nothing happens when I press action while jumping up a ladder. I checked this on the training ground in Lara's home and indeed, she does not grab and climb.

2. The second bizarre thing is that the enemies do not attack. They just sit there and Lara can move around them or shoot them, they just remain still.

Of course with tese 2 "bugs" I cannot play the game. I have no idea if it has anything to do with Java, the driver or anything else... Can you help?...Thank you so much in advance!

**Comment by XProger** [comment]
TR2 features are not implemented yet, you can use cheat mode on O key to pass some zones, but it's not playable, sorry
