### ISSUE TITLE
Tomb of Qualopec area behaves like a movable block

### ISSUE THREAD

**Issue by noiob** [XProger/OpenLara#230]
When holding down X around this area in Tomb of Qualopec (the highest point in the corridor just before the second switch, in the room with the movable platforms), Lara behaves as if she's standing in front of a push/pullable block, even when she's not anywhere near a wall. Pushing up or down doesn't seem to do anything anywhere in the bugged area
![grafik](https://user-images.githubusercontent.com/8197071/68800617-bc0ccc00-065a-11ea-839e-a1cca1eb8c73.png)

**Comment by XProger** [comment]
CNR
