### ISSUE TITLE
Sorry for bothering so much

### ISSUE THREAD

**Issue by Mommy1** [XProger/OpenLara#245]
I'm having another problem, somehow i can control both players at the same time. How do you fix this?

**Comment by XProger** [comment]
use gamepads, or remap second player keys, some keyboards have limited keys pressed simultaneously

**Comment by Mommy1** [comment]
What about Ps4 contollers? Does it work with them?

**Comment by XProger** [comment]
yep, google chrome should support DualShock 4

**Comment by Mommy1** [comment]
I even tried letting the second player become the first player but nothing works. :/

**Comment by XProger** [comment]
https://html5gamepad.com/

**Comment by Mommy1** [comment]
Nothing seems to work. :( Is there a way to reset the button mapping?

**Comment by XProger** [comment]
if gamepad tester doesn't work - check your windows settings, device manager etc.

**Comment by Mommy1** [comment]
Can't find the solution. :/ Idk i'll try again tomorrow maybe it will be fixed then. Thank you for your help though, i appriciate it. :)
