### ISSUE TITLE
No voice in training level

### ISSUE THREAD

**Issue by laenion** [XProger/OpenLara#248]
I'm not sure whether I'm missing something or whether this is caused by my version (German version included in the Gold Games 3 compilation).

Starting the _training level_ / _Lara's House_ on my local PC (_nix_ version) I can see subtitles whenever Lara is supposed to say something, but I don't hear any actual voice. The question is: Where is that voice data supposed to be coming from?

My disc contains 9 audio tracks (including three voiced and localized tracks for the cutscenes), which I have ripped and stored as `audio/0XX.ogg`. When `strace`ing I can see the _OpenLara_ tries to access track **26** and **29** however, which I don't have. When I load the same level in http://xproger.info/projects/OpenLara/ Lara's voiceover is there. I also verified by installing the game in DOSBox that this version _does_ contain voice output...

**Comment by XProger** [comment]
http://xproger.info/projects/OpenLara/files/TR1_audio.7z
