### ISSUE TITLE
Lara en Tomb Raider 2 y 3

### ISSUE THREAD

**Issue by Speak81** [XProger/OpenLara#263]
Lara does not scale, she cannot use the vehicles, level 2 Tomb Raider 2, Venice, you cannot cross the door without the boat.
Tomb Raider 3, Level 3, Lara cannot cross the waterfall to access the cave of level 4.
Is there a trick to pass the level?
Enemies don't work, only tiger works in Tomb Raider 2 and 3. None more, they stay in movement loop.
The levels are beautiful, the resolution and especially the shadows and the effect of the water.

**Comment by XProger** [comment]
For now only TR1 is playable. TR2-4 file formats was reverse engineered and can be played by the engine, but new weapons, enemies, objects and special moves are not implemented yet. To pass some levels you can use cheats like DOZY mode (O key) or skip level (Z X C A Space C X Z)
