### ISSUE TITLE
controls

### ISSUE THREAD

**Issue by XProger** [XProger/OpenLara#27]
- [x] analog support
- [x] assigning keys (from title & inventory screen)

**Comment by mscdex** [comment]
FWIW using Ctrl for shooting is a problem at least in Chrome, as it can cause a browser prompt to occur (perhaps when moving and shooting) asking if you want to stay on the page or leave. This happens quite often and it causes the game to completely freeze when the prompt appears, disrupting the flow of the gameplay.

**Comment by XProger** [comment]
@mscdex Ctrl + W is a browser hotkey (close tab command), so I can't override it. You can use arrow keys instead of WASD in browser.

**Comment by mscdex** [comment]
I guess my comment was more of a +1 to assignable controls.

**Comment by XProger** [comment]
@mscdex this will be when I implement the main menu %)
