### ISSUE TITLE
Black screen until a proper level is loaded

### ISSUE THREAD

**Issue by MaLDox77** [XProger/OpenLara#280]
I had this problem using Retroarch 1.6.1 and I have it with 1.9.0 too.

Files structure is correct and files too.

Loading with retroarch commandline or using retroarch menu to load core and then level, has the same behaviour.

The problem is:

- When loading LEVEL1.PHD, sound from video/cinematic is ok but screen is black. If I skip the cinematic, the loading screen shows for a fraction of a second, and then the level loads correctly and can be played.
- If I enter menu and go to main menu from the level, everything loads correct (no black screen): cinematics, loading screen and levels
- If first I load is TITLE.PHD, sound is ok but screen is black in cinematics and even the menu. I can blindy select to load a level, and only black screen until the level is loaded. Then everything is fine even going back to menu.

So, cinematics and main menu are always black until a level (geometry and characters) are loaded. Then, cinematics and main menu work fine. But not before the level.

Tested in vulkan and gl Retroarch video driver. Tested in fullscreen and windowed. 

With standalone OpenLara there is no issue.

Thank you.

EDIT: I have more info, when playin the level, if I hit "F" key to toggle between fullscreen and windowed, the screen is black and the cinematic sound appears, I have to skip blindly again to see the level. So maybe it's something related to the fullscreen or windowed mode initialization.

**Comment by XProger** [comment]
I didn't work on libretro core, so probably they better know what the problem
https://github.com/libretro/RetroArch/issues/9546

**Comment by MaLDox77** [comment]
> I didn't work on libretro core, so probably they better know what the problem
> [libretro/RetroArch#9546](https://github.com/libretro/RetroArch/issues/9546)

Oh sorry, I mixed project someway.

Thanks for the link.
