### ISSUE TITLE
Some remarks and questions about OpenLara linux and TR2 Gold PC version

### ISSUE THREAD

**Issue by keiem** [XProger/OpenLara#281]
After 20 years, I wanted to play Tomb Raider II again, but this time on linux.  I'm completely new to OpenLara, so I start from a white paper.

I build OpenLara for Linux from commit a94937ae40135b3058b731d3fba9becdffd0dae8 from 5/11/2020.
I use Tomb Raider II Gold for PC (original CD's)

Build went fine, no problems.  Problems appeared with the data files.  The documentation is really barebone...

So it seems the .tr2 files should be in "your_folder/level/2/" directory I also put them in "your_folder/" directory otherwise the game doesn't run.  It's possible only the title.tr2 should be in the "your_folder/" directory. -> Should test it.

Audio should be in "your_folder/audio/2/" transformed from wav to ogg and file naming changed, example Track1.ogg -> track_01.ogg or Track10.ogg -> track_10.ogg

I still have the error when launching a level that some png files are missing for example mansion.png in level/2/ for Lara's mansion.

I'm missing the title picture as mentioned in issue #262 

I'm missing the intro video's but it seems I need also a "your_folder/video/2/" directory.  But this is not a real problem, I don't need the video's.

As I had to search a lot of time how I get everything working, I only had change to practice in Lara's Mansion.  
3 things I notice when practicing:
- When I press alt-ctrl to jump and grab, I get a blue screen pop-up for switching virtual desktops.  Maybe this is related to my DE but it appears in the center of the windowed openlara, so I assume it's inside openlara.
- After a Alt-Crtl press Lara keeps jumping.  I have to press Alt again to let here stop jumping.
- She doesn't want to climb the wall.  This should be done with forward-Ctrl, but she just stays.  First I thought it was because she was in the water, but it's the same on the ground.

Maybe it's because of using the PC version as everybody seems to use the PS version, or maybe it's because I use the keyboard.  Is there a way to change the controls?

**Comment by XProger** [comment]
TR2 is not playable yet, even on PC. You can change buttons mapping in the controls menu.

**Comment by keiem** [comment]
Ah OK, sorry to bother then, I didn't know that.
