### ISSUE TITLE
Switch Version

### ISSUE THREAD

**Issue by AndreDM15** [XProger/OpenLara#282]
on my switch I can't use the controls, just the touch screen, how can I change this?

**Comment by XProger** [comment]
which atmosphere version?

**Comment by AndreDM15** [comment]
Yes

**Comment by XProger** [comment]
yes what? )

**Comment by AndreDM15** [comment]
0.14.3

**Comment by XProger** [comment]
I've 0.10.3 installed, will check on the new version, thanks
