### ISSUE TITLE
TR1 plays cut scene sounds without showing FMV

### ISSUE THREAD

**Issue by zezic** [XProger/OpenLara#283]
When walking trough levels of TR1 I noticed that the `track_08.ogg` and `track_09.ogg` are played at some checkpoints, but the video playback is not initialized.

For example, I'm hearing the `track_09.ogg` on background when walking here:
![Screenshot_20201214_011122](https://user-images.githubusercontent.com/1945127/102025481-3dc4b100-3da9-11eb-8243-6cd9b1c59c19.png)

I'm running pre-compiled Linux version (f145f0b) with the next directory structure:
<details>
<summary>tree --dirsfirst output:</summary>

```bash
zezic@990FXA:~/Documents/Soft/Games/OpenLara_nix/gog$ tree --dirsfirst
.
├── audio
│   └── 1
│       ├── track_02.ogg
│       ├── track_03.ogg
│       ├── track_04.ogg
│       ├── track_05.ogg
│       ├── track_06.ogg
│       ├── track_07.ogg
│       ├── track_08.ogg
│       ├── track_09.ogg
│       └── track_10.ogg
├── level
│   └── 1
│       └── AMERTIT.PNG
├── video
│   └── 1
│       ├── CAFE.RPL
│       ├── CANYON.RPL
│       ├── CORE.RPL
│       ├── END.RPL
│       ├── ESCAPE.RPL
│       ├── LIFT.RPL
│       ├── MANSION.RPL
│       ├── PRISON.RPL
│       ├── PYRAMID.RPL
│       ├── SNOW.RPL
│       └── VISION.RPL
├── CRED1.PCX
├── CRED2.PCX
├── CRED3.PCX
├── CUT1.PHD
├── CUT2.PHD
├── CUT3.PHD
├── CUT4.PHD
├── EIDOSPC.PCX
├── END.PCX
├── GYM.PHD
├── INSTALL.PCX
├── LEVEL10A.PHD
├── LEVEL10B.PHD
├── LEVEL10C.PHD
├── LEVEL1.PHD
├── LEVEL2.PHD
├── LEVEL3A.PHD
├── LEVEL3B.PHD
├── LEVEL4.PHD
├── LEVEL5.PHD
├── LEVEL6.PHD
├── LEVEL7A.PHD
├── LEVEL7B.PHD
├── LEVEL8A.PHD
├── LEVEL8B.PHD
├── LEVEL8C.PHD
├── OpenLara
├── TITLEH.PCX
└── TITLE.PHD

6 directories, 50 files
```

</details>

**Comment by XProger** [comment]
you have wrong audio probably from GOG or Steam, which is lazy port of the original game on PC. Use PSX data and sounds pack below. Just extract it to the empty folder and run the game from it without moving any files.

data http://xproger.info/projects/OpenLara/files/TR1_data.7z
audio http://xproger.info/projects/OpenLara/files/TR1_audio.7z

**Comment by zezic** [comment]
Thank you!
