### ISSUE TITLE
Audio stutters

### ISSUE THREAD

**Issue by zezic** [XProger/OpenLara#285]
With TR1 the audio effects are having some stutters. Music seems to play without problem.
I'm using the data files mentioned in https://github.com/XProger/OpenLara/issues/283#issuecomment-744181796
My OS kernel is
```
Linux 990FXA 5.4.0-56-lowlatency #62-Ubuntu SMP PREEMPT Mon Nov 23 20:19:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
I've tried the binary build found in OpenLara_nix.zip on the releases section (f145f0b). Also I tried to compile both the nix and sdl2 versions (cee187309322fa3a5a9b450d0dfd91e6d736d045). I'm using PulseAudio, but other apps are working fine.

Sometimes the stutter disappears for some period, for example, after changing the window size, but after a while it comes back.

Here is the stuttering of the "whooosh" sound (blade trap):
![Screenshot_20201215_220458](https://user-images.githubusercontent.com/1945127/102261802-43460680-3f23-11eb-9c85-c4132b9d38c0.png)

The length of the selected region is 16 samples.

**Comment by zezic** [comment]
Audio example (volume normalized)
[tr-stutters.zip](https://github.com/XProger/OpenLara/files/5698157/tr-stutters.zip)

**Comment by XProger** [comment]
https://github.com/XProger/OpenLara/blob/master/src/platform/nix/main.cpp#L30 try to use 2352 instead of 1024 here

**Comment by zezic** [comment]
It did the trick! Thank you.

**Comment by XProger** [comment]
Can you make pull request?
