### ISSUE TITLE
High resolution videos 

### ISSUE THREAD

**Issue by MaLDox77** [XProger/OpenLara#288]
Hi,
I tried everything to use hires cutscenes but no luck. Files from steam version don’t work.

Is there a way?

**Comment by XProger** [comment]
Steam version has the original RPL (Escape codec) FMVs. What you are trying to do?

**Comment by MaLDox77** [comment]
> Steam version has the original RPL (Escape codec) FMVs. What you are trying to do?

To use the high res versions in Open Lara.

**Comment by XProger** [comment]
only original video files are supported
