### ISSUE TITLE
Wolf under water?

### ISSUE THREAD

**Issue by HMAZonderland** [XProger/OpenLara#29]
Found a wolf under water. Does not seem to happen? 

OSX 10.12.4 
Chrome 57.0.2987.133 64-bit

<img width="678" alt="screen shot 2017-04-25 at 13 48 34" src="https://cloud.githubusercontent.com/assets/4153366/25383926/705542b8-29be-11e7-935d-2a0d5e641c3c.png">
<img width="332" alt="screen shot 2017-04-25 at 13 47 19" src="https://cloud.githubusercontent.com/assets/4153366/25383925/70506a5e-29be-11e7-9deb-f2abf11ad091.png">

**Comment by bosskhalif** [comment]
I think it's a bug !

**Comment by CDrosos** [comment]
it might be a pretty clever wolf

**Comment by XProger** [comment]
fixed c4ab64dec68babf4be7476ccd9ea13ea9c10df47
