### ISSUE TITLE
Ambient sound issue

### ISSUE THREAD

**Issue by Leo-89** [XProger/OpenLara#299]
Hi. I got the new release of the day with the hope to fix ambient sound in certain levels. 
Unluckily many levels still don't have this feature in the updated Windows version; I refer to all Greece levels (with the exception of Colosseum) and Egypt levels I played so far (I'm just testing Obelisk of Khamoon). :///
I can hear only the ambient sound featured in the first level every time it's reused; I never heard other ones.

**Comment by XProger** [comment]
do you have android version ogg tracks?

**Comment by Leo-89** [comment]
Yes, I think it's Android version .ogg tracks but caves ambient sound and other sounds work flawlessly. Is there a solution? :///

**Comment by XProger** [comment]
http://xproger.info/projects/OpenLara/files/TR1_audio.7z

**Comment by Leo-89** [comment]
Thank you so much!
