### ISSUE TITLE
JavaScript errors / game won't load

### ISSUE THREAD

**Issue by inboudayo** [XProger/OpenLara#31]
I'm using Linux Mint 17 Cinnamon 64-bit, tested in Chrome Version 58.0.3029.81:

Exception thrown, see JavaScript console
Uncaught TypeError: Cannot read property 'getSupportedExtensions' of undefined

Also tested in FireFox Version 53.0:

Gah. Your tab just crashed.

**Comment by XProger** [comment]
Please check your browser for WebGL support http://webglreport.com/

**Comment by inboudayo** [comment]
Thanks. That page indicated that the browser (Chrome) supports WebGL but it was disabled or unavailable, and recommended updating my video drivers. I updated from nvidia-340 to nvidia-375 and now it's working.
