### ISSUE TITLE
no display on  OGA 

### ISSUE THREAD

**Issue by sunxuold** [XProger/OpenLara#329]
Dear XProger 
    I use lastest code (2021/03/02) to compile for OGA  but it can not show any display  screen is black  and i  can hear sound it seems OK ， can u help me to correct  it ?   Thanks!

below  is i compile commond 
/opt/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-g++ -I/opt/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu/aarch64-none-linux-gnu/include/  --sysroot=/opt/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu/aarch64-none-linux-gnu  -DSDL2_GLES -D_GAPI_GLES2 -std=c++11 `sdl2-config --cflags` -O2 -mcpu=cortex-a35  -ffast-math -fPIC -Wall -fomit-frame-pointer -Wno-write-strings -Wno-long-long -Wno-sign-compare -Wno-uninitialized -Wno-unused -Wno-conversion -Wno-attributes -Wno-unused-parameter -Wno-unused-value  -fno-exceptions -fno-rtti -ffunction-sections -fdata-sections -Wl,--gc-sections -DNDEBUG -D__SDL2__ main.cpp ../../libs/stb_vorbis/stb_vorbis.c ../../libs/minimp3/minimp3.cpp ../../libs/tinf/tinflate.c -I../../ -o OpenLara -lSDL2 -lrga -lGLESv2 -lEGL -lm -lrt -lpthread -lasound -ludev

this is output info when i run with demo  data
./OpenLara ./LEVEL2.PSX  >>test.log

Rga built version:version:+2017-09-28 10:12:42 
rk-debug mali-ver=rsx-p0-1.2
windows size 480 x 320 
OpenLara (Mar  1 2021)
Vendor   : (null)
Renderer : (null)
Version  : (null)
cache    : /home/user/.openlara/
supports :
  variyngs count : 0
  binary shaders : false
  vertex arrays  : false
  depth texture  : false
  shadow sampler : false
  discard frame  : false
  NPOT textures  : false
  3D   textures  : false
  RG   textures  : false
  border color   : false
  max level      : false
  anisotropic    : 0
  float textures : float = false, half = false

shader: cache warm-up...
shader: cache is ready
meshes: 181
rooms   : 1024 x 1024
objects : 1024 x 512
sprites : 512 x 512
glyphs  : 1024 x 512
MegaMesh (i:114996 v:50641 a:3, size:1850504)
Read Slots...
FPS: 0 DIP: 1 TRI: 10 RT: 0
FPS: 0 DIP: 1 TRI: 10 RT: 0
status: 0x0000
status: 0x0000
FPS: 60 DIP: 11 TRI: 2207 RT: 2

**Comment by XProger** [comment]
```
Vendor : (null)
Renderer : (null)
Version : (null)
```
does this device have OpenGL support?

**Comment by sunxuold** [comment]
> ```
> Vendor : (null)
> Renderer : (null)
> Version : (null)
> ```
> 
> does this device have OpenGL support?

OGA use RK3326 chip 
CPU: Quad-Core ARM Cortex-A35, up to 1.5GHz  
GPU: Mali-G31 GPU, support OpenGL ES3.2, Vulkan 1.0, OpenCL 2.0
so it should support  GLES  any limitation?

**Comment by sunxuold** [comment]
> ```
> Vendor : (null)
> Renderer : (null)
> Version : (null)
> ```
> 
> does this device have OpenGL support?

Dear XProger：
    I think i got the reason and   this branch https://github.com/libretro/OpenLara (libretro platform) can work on OGA after some modification.
the main reason is we must make code use GLES 3.x   only not OpenGL for OGA . and even in GLES mode we must make below part always false:
support.shadowSampler  = false;  //extSupport(ext, "_shadow_samplers") || extSupport(ext, "GL_ARB_shadow");

   i  try to merge the two branch's  code but fail , can u tell  me how to complete it 
                                                                                                                                                                                        Thanks

**Comment by XProger** [comment]
@sunxuold did you manage what the problem with shadowSampler and why it's not OGLES by default for OGA? Which _OS_* define was declared for OGA? I suppose it should be _OS_ANDROID but you get _OS_LINUX for some reason. If it's true then just add /DANDROID to tge compiler cmd line.

**Comment by sunxuold** [comment]
> @sunxuold did you manage what the problem with shadowSampler and why it's not OGLES by default for OGA? Which _OS_* define was declared for OGA? I suppose it should be _OS_ANDROID but you get _OS_LINUX for some reason. If it's true then just add /DANDROID to the compiler cmd line.

hi XProger :
   because i  startup the so file  and got shadow sampler : false in log output, then the disolay is output but not correctly , so i changed the code make shadow sampler  always false , it will make display correct on OGA.
       OGA OS is ubuntu 20.04  so the OS is linux. but only support GLSE.   Can i use  /DANDROID in this case?  please let me know , Thanks.

**Comment by XProger** [comment]
![image](https://user-images.githubusercontent.com/796763/112421052-6ad91600-8d3f-11eb-9178-4721efbb933f.png)
try to add this line in core.h

**Comment by sunxuold** [comment]
> @sunxuold did you manage what the problem with shadowSampler and why it's not OGLES by default for OGA? Which _OS_* define was declared for OGA? I suppose it should be _OS_ANDROID but you get _OS_LINUX for some reason. If it's true then just add /DANDROID to the compiler cmd line.

> ![image](https://user-images.githubusercontent.com/796763/112421052-6ad91600-8d3f-11eb-9178-4721efbb933f.png)
> try to add this line to core.h

i use this way to build on SDL2 branch  but got same issue on any display the log show:  
use -DSDL2_GLES   in building

run log out put:
supports :
  variyngs count : 0
  binary shaders : false
  vertex arrays  : false
  depth texture  : false
  shadow sampler : false
  discard frame  : false
  NPOT textures  : false
  3D   textures  : false
  RG   textures  : false
  border color   : false
  max level      : false
  anisotropic    : 0
  float textures : float = false, half = false

but i run that libertro verion got those output  and work fine
supports :
  variyngs count : 15
  binary shaders : true
  vertex arrays  : true
  depth texture  : true
  shadow sampler : false
  discard frame  : true
  NPOT textures  : true
  3D   textures  : true
  RG   textures  : true
  border color   : true
  clip distance  : false
  anisotropic    : 0
  float textures : float = full, half = full

so i think  the reason is SDL2 version  try to open OpenGL noy GLES  any way to fix it?

**Comment by XProger** [comment]
@vanfanel your turn ;)

**Comment by sunxuold** [comment]
i also  try those  way  on SDL 2 branch
1,   -DSDL2_GLES -D_GAPI_GLES    same problem  no display

2,   -DSDL2_GLES -D_GAPI_GLES2 -D_GAPI_GLES   or  ( -DSDL2_GLES -D_GAPI_GLES2 )  cannot build 

/gl.h:935:29: error: ‘GL_R8’ was not declared in this scope; did you mean ‘GL_RG’?
gl.h:936:29: error: ‘GL_RED’ was not declared in this scope; did you mean ‘GL_RG’
/gl.h:1193:13: error: ‘glGetStringi’ was not declared in this scope;
gl.h:1195:27: error: ‘GL_NUM_EXTENSIONS’ was not declared in this scope

**Comment by sunxuold** [comment]
well well i [complete] merge libretro  into current code for OGA now it work fine  u can check it may merge to main branch (`url
[OpenLaraOGA.zip](https://github.com/XProger/OpenLara/files/6202781/OpenLaraOGA.zip)
`)

**Comment by sunxuold** [comment]
@XProger  @vanfanel  pls check my append code may not a best way to handle.

**Comment by vanfanel** [comment]
@sunxuold Sorry, I am not opening a ZIP with some sources an compare manually.
I will gladly look at what you did to fix this, but please do a proper fork and PR so I can clearly see the changes.

Thanks

**Comment by sunxuold** [comment]
> @sunxuold Sorry, I am not opening a ZIP with some sources an compare manually.
> I will gladly look at what you did to fix this, but please do a proper fork and pull request so I can clearly see the changes.
> 
> OpenLara on SDL2 works using GLES2, GLES3 or OpenGL, not GLES1.
> 
> You can look at this file to see what you are building OpenLara/SDL2 against:
> https://github.com/XProger/OpenLara/blob/master/src/platform/sdl2/build.sh
> You shouldn't be passing any -D parameters manually, use one of the build lines on that file.
> 
> Thanks

Fine  i will creat a new pull request for it .  and  for my test  the GLES file used by SDL2 part  not compatible for OGA, and  i use GELS file from libretro it can work for OGA,  but it is too complex for me to find the different between SDL2 and libretro  so i focus on libretro part only now.
