### ISSUE TITLE
Is enemies IA worst in last versions?

### ISSUE THREAD

**Issue by Leo-89** [XProger/OpenLara#339]
Replaying some levels like Lost Valley and Colosseum I noticed that some enemies are less aggressive than before.
The little dinosaurs in Lost Valley and two lions at the beginning of Colosseum seem to run away from Lara instead of attack her.
Is it my impression or enemies have accidentally been "downgraded" in last OL version?
Thank you! :)

**Comment by XProger** [comment]
nope, still the same dumb enemies
