### ISSUE TITLE
Unable to bind slow motion key on 3ds

### ISSUE THREAD

**Issue by angermanaged** [XProger/OpenLara#341]
I saw a video where, on the browser version at least, this guy was able to activate slow motion by pressing a key on his keyboard. not sure if i did something wrong during installation or what, but i cant find out how to bind it to a button no matter how much i look into it.

**Comment by XProger** [comment]
T, R, O, 5, 6 and P keyboard keys are reserved for debugging purposes only and may be unavailable for different platforms. So 3DS and other non-keyboard platforms can't use it.
