### ISSUE TITLE
Tr1

### ISSUE THREAD

**Issue by Pedko** [XProger/OpenLara#343]
I can't play openlara when I assign the controls for the keyboard it does the same for the controller and I don't want that and if I move with my keyboard the other character moves too

**Comment by XProger** [comment]
you can assign gamepad index or keyboard controls for each player in the controls settings

**Comment by Pedko** [comment]
> you can assign gamepad index or keyboard controls for each player in the controls settings

But that's the problem it doesn't assign it properly if I choose player 1 keyboard it chooses it for player 2 too that's the problem

**Comment by XProger** [comment]
![image](https://user-images.githubusercontent.com/796763/113351019-eee45c80-9342-11eb-90cc-9aefd93d1dbe.png)
can't see any problem here
