### ISSUE TITLE
macOS Big Sur Support

### ISSUE THREAD

**Issue by perkinsj8** [XProger/OpenLara#349]
_EDIT_: OpenLara **IS COMPATIBLE** on Big Sur/ M1 processors. Tested in both Safari and the standalone app on macOS Big Sur via a M1-based Mac Mini! Minor visual artifacts noticed on skybox in The Lost Valley and The Colosseum levels.

**Comment by XProger** [comment]
It would be great if someone from M1 owners will port the game (it should be easy task), but I don't have such hardware yet and don't have a plan to buy it

**Comment by dmitshur** [comment]
> the standalone app isn't yet compatible

Which standalone app are you referring to, and in what way is it not compatible?

I was able to build and run OpenLara from source on an M1 MacBook Air running Big Sur without making any code changes. The only tricky part was getting it to look in the right directory for data files, because I didn't find much documentation on that.

**Comment by perkinsj8** [comment]
Maybe an update to the OS has fixed compatibility issues with the standalone app (from your GitHub page). I’ll test it out too and let you know.

**Comment by perkinsj8** [comment]
Okay, it seems the Open Lara standalone app didn't work for me because I didn't have the DATA files plugged into the directory nor access to .exe files (ex. dosbox.exe) due to being on Mac. Also, from my knowledge the GOG version doesn’t have direct access to the DATA files without installing TR1 firsthand whereas TR2-5 does provide these files from the get go. With that said, the standalone app probably would work so that was my error due to lack of files in Contents/Resources.

**Comment by XProger** [comment]
data http://xproger.info/projects/OpenLara/files/TR1_data.7z
audio http://xproger.info/projects/OpenLara/files/TR1_audio.7z

please check and comment out, I'll remove this comment

**Comment by perkinsj8** [comment]
With above files in the Contents/Resources I can confirm that OpenLara (Standalone app) successfully runs on Mac Mini M1.

**Comment by perkinsj8** [comment]
Done. Also, is there a level skip option or debug menu to select level? The standard PC level cheat does not work and I assume that is because the Data files are PSX based?

**Comment by XProger** [comment]
@perkinsj8 for the default keys mapping press one of those sequences right in the game:
level skip - Z X C A Space C X Z
all weapons - C Space X Z Z X A C
i.e.
CHEAT_ALL_WEAPONS[] = { cLook, cWeapon, cDash, cDuck, cDuck, cDash, cRoll, cLook };
CHEAT_SKIP_LEVEL[]  = { cDuck, cDash, cLook, cRoll, cWeapon, cLook, cDash, cDuck };

**Comment by perkinsj8** [comment]
![Screen Shot 2021-06-21 at 9 40 50 AM](https://user-images.githubusercontent.com/78816180/122771971-ed0ca400-d274-11eb-8cff-ec2062d0d6a4.png)

Thanks for the cheats. Also, not really big issue, but there are some artifacts in the skyboxes (on M1 based Macs) that was not present when playing on an intel-based MacBook Air (2015). Regardless, it barely effects gameplay. The water shaders still appear fine on my Mac mini M1.

**Comment by XProger** [comment]
Skybox require 3D texture support in HW.

**Comment by dmitshur** [comment]
> I was able to build and run OpenLara from source on an M1 MacBook Air running Big Sur without making any code changes.

Sorry, that's not quite true. There was one minor change I had to do to fix a build error related to OpenGL. I've reported it in #354, and can send a PR with a fix if it's helpful.
