### ISSUE TITLE
src/platform/osx: build error on macOS Big Sur on Apple silicon due to undeclared OpenGL 3.0+ identifiers

### ISSUE THREAD

**Issue by dmitshur** [XProger/OpenLara#354]
When building from source on a MacBook Air with M1 (macOS Big Sur 11.4, Xcode 12.5.1), using the Xcode project in `src/platform/osx` directory, there are uses of the following undeclared identifiers in `src/gapi/gl.h` that cause build errors:

- `glGetStringi`
- `GL_NUM_EXTENSIONS`

Those identifiers are defined in OpenGL 3.0 and later, but `src/platform/osx` (on macOS) seems to target OpenGL 2.1 at this time.

<details><summary>Why OpenGL 2.1?</summary><br>

Specifically, in `src/gapi/gl.h`, under macOS case (when `__APPLE__` is defined but `_OS_IOS` is not):

```
#include <OpenGL/gl.h>
```

And in `src/platform/osx/main.mm`, a legacy OpenGL context is requested:

```
NSOpenGLPFAOpenGLProfile, NSOpenGLProfileVersionLegacy,
```

Which results in `GL_VERSION` having the value "2.1 Metal - 71.6.4".

<details><summary>What about OpenGL 4.1?</summary><br>

For reference, a 4.1 core profile can be successfully requested with:

```
NSOpenGLPFAOpenGLProfile, NSOpenGLProfileVersion4_1Core,
```

That results in `GL_VERSION` being "4.1 Metal - 71.6.4".

But shaders fail to compile because they don't have the `#version` directive which becomes mandatory.

</details>
</details>

**Comment by dmitshur** [comment]
There are many different ways the build error can be fixed.

For example, a local `#ifdef` can be added to `extSupport`:

```diff
     bool extSupport(const char *str) {
+        #if defined(glGetStringi) && defined(GL_NUM_EXTENSIONS)
             if (glGetStringi != NULL) {
                 GLint count = 0;
                 glGetIntegerv(GL_NUM_EXTENSIONS, &count);
                 for (int i = 0; i < count; i++) {
                     const char *ext = (const char*)glGetStringi(GL_EXTENSIONS, i);
                     if (strstr(ext, str) != NULL) {
                         return true;
                     }
                 }
-            } else {
+            } else
+        #endif
+        {
             const char *ext =  (const char*)glGetString(GL_EXTENSIONS);
             if (!ext) {
                 return false;
```

This should be very safe—it can't break any other platforms—but adds verbosity.

Alternatively, instead of checking whether `glGetStringi` and `GL_NUM_EXTENSIONS` are defined, you could add a guard for `GL_VERSION_3_0` being defined (and non-zero):

```diff
-        #if defined(glGetStringi) && defined(GL_NUM_EXTENSIONS)
+        #if GL_VERSION_3_0
```

That makes it a little more clear that that section requires OpenGL 3.0+ features.

Finally, it might be a better idea to just import the `gl3.h` header instead of `gl.h`, which defines everything for OpenGL 3.0+. Then no changes need to be applied to `extSupport`, and `src/gapi/gl.h` can be simplified:

```diff
         #include <Carbon/Carbon.h>
         #include <AudioToolbox/AudioQueue.h>
         #include <OpenGL/OpenGL.h>
-        #include <OpenGL/gl.h>
-        #include <OpenGL/glext.h>
+        #include <OpenGL/gl3.h>
         #include <AGL/agl.h>
-
-        #define GL_RG                       0x8227
-        #define GL_RG16F                    0x822F
-        #define GL_RG32F                    0x8230
-        #define GL_RGBA16F                  0x881A
-        #define GL_RGBA32F                  0x8814
-        #define GL_HALF_FLOAT               0x140B
-
-        #define GL_RGB565                   GL_RGBA
-        #define GL_TEXTURE_COMPARE_MODE     0x884C
-        #define GL_TEXTURE_COMPARE_FUNC     0x884D
-        #define GL_COMPARE_REF_TO_TEXTURE   0x884E
-
-        #define glGenVertexArrays    glGenVertexArraysAPPLE
-        #define glDeleteVertexArrays glDeleteVertexArraysAPPLE
-        #define glBindVertexArray    glBindVertexArrayAPPLE
-
-        #define GL_PROGRAM_BINARY_LENGTH 0
-        #define glGetProgramBinary(...)  0
-        #define glProgramBinary(...)     0
     #endif
```

However, I haven't tested that this change doesn't break the Intel-based macOS build. That would need to be done, if you prefer this direction, to avoid a whack-a-mole situation.

I would send a PR but I don't know what approach you prefer. Feel free to fix the issue yourself, or if it helps, I can send a PR with your preferred fix.

**Comment by XProger** [comment]
gl3.h would be better solution, thanks
