### ISSUE TITLE
shadows on macOS don't work unless GL_RGB565 is redefined

### ISSUE THREAD

**Issue by dmitshur** [XProger/OpenLara#360]
Now that high quality water is fixed on macOS (issue #356), I noticed there was another smaller graphical regression unfortunately introduced by PR #355. (Sorry! I'm pretty sure it's the last one.)

Specifically, one of the lines it removed wasn't just defining the `GL_RGB565` constant, but rather it was _redefining_ it to another value:

```C++
#define GL_RGB565                   GL_RGBA
```

Without that redefinition, the shadows don't render properly (on both Macs I tried, including Intel-based and Apple silicon), and there's a warning printed inside [`bindTarget`](https://github.com/XProger/OpenLara/blob/dfe0dcb3f288bd582fd9d717e771eec5eba44afe/src/gapi/gl.h#L1555) because `glCheckFramebufferStatus` no longer returns `GL_FRAMEBUFFER_COMPLETE`:

```
[...]
status: 0x8CD6
status: 0x8CD6
status: 0x8CD6
[...]
```

(That status is "framebuffer incomplete".)

## Fix

A straightforward fix is to bring back the `GL_RGBA565` redefinition, as it was present before PR #355, perhaps with a comment explaining why it's being redefined:

```C++
// TODO: Explanation.
#undef GL_RGB565
#define GL_RGB565 GL_RGBA
```

Another option is to update the call sites. There's only one place where `GL_RGB565` is used in the entire codebase, and it's inside `cacheRenderTarget`:

https://github.com/XProger/OpenLara/blob/dfe0dcb3f288bd582fd9d717e771eec5eba44afe/src/gapi/gl.h#L1532

It can just be updated there to use `GL_RGBA` instead, if that's what's intended (and works for all platforms).

If it should only be `GL_RGBA` on macOS but not other platforms, then perhaps:

```diff
+#if !_OS_MAC
     glRenderbufferStorage(GL_RENDERBUFFER, depth ? GL_DEPTH_COMPONENT16 : GL_RGB565, width, height);
+#else
+    glRenderbufferStorage(GL_RENDERBUFFER, depth ? GL_DEPTH_COMPONENT16 : GL_RGBA, width, height);
+#endif
```

@XProger I'm able to send a PR—if it helps—if you tell me which path you prefer.

**Comment by XProger** [comment]
RGBA textures are used for shadows on potato-PCs. I suppose you have both support.depthTexture and support.shadowSampler == false for some reason?

**Comment by dmitshur** [comment]
That is not the case, both are true:

```
vertex arrays  : true
depth texture  : true
```

<details><br>

```
OpenLara (Jun 28 2021)
Vendor   : Apple
Renderer : Apple M1
Version  : 2.1 Metal - 71.6.4
cache    : $HOME/Library/Application Support/OpenLara/
supports :
  variyngs count : 16
  binary shaders : false
  vertex arrays  : true
  depth texture  : true
  shadow sampler : true
  discard frame  : false
  NPOT textures  : true
  3D   textures  : true
  RG   textures  : true
  border color   : true
  max level      : false
  anisotropic    : 16
  float textures : float = full, half = full
```

</details>

Things seem to work if `GL_RGB8` is used instead of `GL_RGB565`, maybe that's a more compatible "high end" internal storage format to use?

**Comment by XProger** [comment]
Potato-PCs shadows require four 8-bit channels, i.e. GL_RGBA8. macOS shouldn't use this code path anyway.

**Comment by dmitshur** [comment]
> Potato-PCs shadows require four 8-bit channels, i.e. GL_RGBA8.

I see. I tried it, `GL_RGBA8` works too.

> macOS shouldn't use this code path anyway.

I'm not sure why or what you're suggesting instead.

(If I can of help to resolve this issue, let me know what fix you'd like me to send. I'm happy to leave this to you to fix if that's easier. Thanks!)

**Comment by XProger** [comment]
ah, I understand, glRenderbufferStorage for depth based shadows uses GL_RGB565 as dummy texture, you can define it as GL_RGBA if for some reason macOS can't render into 16-bit, but other platforms still can use 16-bit render targets and save some memory. So
```C++
#undef GL_RGB565
#define GL_RGB565 GL_RGBA
```
would be good solution for macOS.
