### ISSUE TITLE
Broken Secret.

### ISSUE THREAD

**Issue by Arquivista** [XProger/OpenLara#364]
I've recently noticed that playing with OpenLara it's impossible to get the secret of the waterfall in the third stage (lost valley) because it doesn't walk to the middle of the hanging waterfall as it should, it stops halfway.

The problem happens with both PS1 and PC version files.
![Screenshot_1](https://user-images.githubusercontent.com/30628523/124415055-66eb6580-dd2a-11eb-8b98-78868320b872.jpg)

**Comment by XProger** [comment]
#123
