### ISSUE TITLE
TB1 tombe de tihocan

### ISSUE THREAD

**Issue by ghost** [XProger/OpenLara#373]
Lara can't get to the door.
She climbs into the void.
![tomb1 tombe de tihocan](https://user-images.githubusercontent.com/77933011/140622579-56db0867-cc78-489d-b269-42dcc2184de1.jpg)
![tomb1 tombe de tihocan2](https://user-images.githubusercontent.com/77933011/140622582-dd3fae20-cbc0-48c2-a4b9-f1193240fe1e.jpg)
![Capture d’écran du 2021-11-06 21-09-41](https://user-images.githubusercontent.com/77933011/140622583-87b9bc88-ba0b-4ba7-9cf5-e3f9e4d06586.png)

**Comment by jackysee** [comment]
I've got the same problem on the latest android build (24.14.22). She goes up when pressing left while holding onto the ledge, so she can never reach the door.

**Comment by XProger** [comment]
Hi, this is known bug, for now you can press O key or Walk, Look, Walk, Look, Walk, Look, Walk, Look to go DOZY mode and pass this room
