### ISSUE TITLE
TR3 GOG, bugs report

### ISSUE THREAD

**Issue by legluondunet** [XProger/OpenLara#380]
Hello,
I just compiled OpenLara and try to play TR3.
I own the GOG version.
First, if I copy OpenLara binary in main TR3 install folder, it doesn't launch.
I have to respect this tree folder organisation:
DATA --> level/3
audio --> audio/3
fmv --> video/3

Then when I launch OpenLara, video cutscenes playing well but mainmenu has no background:

![Capture d’écran_2021-12-26_23-12-04](https://user-images.githubusercontent.com/325405/147421151-60681606-7907-4e61-8a81-9e9deae41625.png)

Then, I start the game but I can no go far than this point:
![Capture d’écran_2021-12-26_23-13-59](https://user-images.githubusercontent.com/325405/147421174-03e2e393-bb97-407f-a4b4-26244f041cdc.png)

I can no more move Lara.

Thank you for your help.

Config:
Linux

**Comment by XProger** [comment]
OpenLara only supports TR1 completely for now
