### ISSUE TITLE
Game appears in task manager for a bit, then closes

### ISSUE THREAD

**Issue by P33P33M4N2** [XProger/OpenLara#396]
After opening the game, it would appear in task manager, then close itself. I already reinstalled it, but nothing changed. Any help?

**Comment by XProger** [comment]
how the game folder structure looks like?

**Comment by P33P33M4N2** [comment]
also i tried running in admin and it gave me thi
![bruh2](https://user-images.githubusercontent.com/98390275/150977250-5af1b8fc-12a1-40d8-9a25-248af017668f.png)
s

**Comment by XProger** [comment]
try this
data http://xproger.info/projects/OpenLara/files/TR1_data.7z
audio http://xproger.info/projects/OpenLara/files/TR1_audio.7z

**Comment by P33P33M4N2** [comment]
Where do I put the files? I'm using the PS1 release

**Comment by P33P33M4N2** [comment]
nvm, i found out where but it didn't fix the problem

**Comment by XProger** [comment]
Can you please check the console output of the debug version?
[OpenLara_debug.zip](https://github.com/XProger/OpenLara/files/7945329/OpenLara_debug.zip)

**Comment by P33P33M4N2** [comment]
it just shows this then closes agai
![bruh3](https://user-images.githubusercontent.com/98390275/151343795-a3ea9933-c599-4f1b-a8dd-72de3384ff90.png)
n

**Comment by XProger** [comment]
@P33P33M4N2 no graphics driver installed

**Comment by P33P33M4N2** [comment]
so uh how do i fix that

**Comment by XProger** [comment]
download and install graphics drivers for your graphics card

**Comment by P33P33M4N2** [comment]
alr right before attempting to update graphics drivers my pc turned off and started smoking but now its good but the card is gone and all the stuff earlier now says null

**Comment by XProger** [comment]
sorry, can't help witth hw problems
