### ISSUE TITLE
collisions

### ISSUE THREAD

**Issue by XProger** [XProger/OpenLara#4]
- [x] correct collision and wall offsets
- [x] walk through portal
- [x] static meshers (collision bbox)
- [x] enemies
- [x] bridge

**Comment by rr-** [comment]
The project looks fantastic!

![20170425_224238_coj](https://cloud.githubusercontent.com/assets/1045476/25406945/cde315dc-2a08-11e7-9a77-77b1a00aa105.png)

This has happened to me when I stood near the water and tried to do a standing jump forward, not sure if this report is of value but here it is anyway.

**Comment by CDrosos** [comment]
One enemy can go inside the other:
https://snag.gy/UehpaL.jpg
here two wolfs are almost completely one inside the other

**Comment by Gh0stBlade** [comment]
@CDrosos 

Probably better to open a new issue for this. I wouldn't call it a collision bug, more of a path finding error.
