### ISSUE TITLE
Graphical Bugs

### ISSUE THREAD

**Issue by Gh0stBlade** [XProger/OpenLara#40]
Level: LEVEL7B (Tomb of Tihocan)
Room: 20
Lara Position: 57879, 0, 16143.

Issue:
Water ripple effect does not work in this water room.
http://i.imgur.com/CxTSpmx.png

Issue 2:
http://i.imgur.com/YXurpuy.png

Strange flickering graphical artifacts occur at the ceiling of certain water rooms. This is likely the water ripple shader. Also occurs in LEVEL10B (Atlantis).

**Comment by XProger** [comment]
fixed in a89e3f8bebc9c142e9bc0aa5daa5cb1c671f8422
