### ISSUE TITLE
how can i  do save game at any time in android branch

### ISSUE THREAD

**Issue by sunxuold** [XProger/OpenLara#417]
hi :
   i build the  lastest code  and put the game data (TR1 PC and PCX version )at correct path .  but when i entry then level
i can not do save game  operation.  can u tell me how to make it happen? i want save game at any time. 
                                                                                                                                                     thanks.

**Comment by XProger** [comment]
Did you get error message when trying to save? If yes - check the app access permissions, write to internal storage must be enabled.
Use 5/9 keys on keyboard connected to android device, to test save/load ability. There is no binding for touch screen or passport so...

**Comment by sunxuold** [comment]
can we support use game menu  to save game at any time?

**Comment by sunxuold** [comment]
> Did you get error message when trying to save? If yes - check the app access permissions, write to internal storage must be enabled. Use 5/9 keys on keyboard connected to android device, to test save/load ability. There is no binding for touch screen or passport so...

can we support use game menu to save game at any time? it will become same with  orig game save way

**Comment by XProger** [comment]
yep, the new "fixed" version will have the og PC style save menu

**Comment by sunxuold** [comment]
> yep, the new "fixed" version will have the og PC style save menu

Well done, can i  use it in android version directly?

**Comment by XProger** [comment]
no, work in progress

**Comment by sunxuold** [comment]
OK, now i add one touch area on top middle screen for quick save.
