### ISSUE TITLE
TR1 Sanctuary of the Scion

### ISSUE THREAD

**Issue by VinceWhirlwind** [XProger/OpenLara#428]
First of all, let me convey my thanks to you for the extraordinary work you've done to renew, revitalise and conserve this classic game for all of us to enjoy once more and in perpetuity. It is very much appreciated.

Now, on to the issue: I'm using Chrome Browser with Mac OS Monterey 12.3.1. 

In the Sanctuary of the Scion, in the side area to the right of the Sphinx with the slope, stairs, pool and bridge, Lara is supposed to be able to traverse from the foot of the slope onto the bridge. But, in this instance, she can't. It stops the game dead, as this means she can't obtain the second Ankh that will enable her to proceed through the rest of the game.

I've also noticed issues with traversal elsewhere in this level; Lara just slides a bit from side to side on the edge of platforms but doesn't animate like she should and can't reach her objective.

Best wishes

Glenn

**Comment by XProger** [comment]
Hi, thanks and sorry, it's a known bug, you can do some tricky jump to pass it https://youtu.be/Vi1bjaBtYDU?t=830 or just press O key for dozy mode

**Comment by VinceWhirlwind** [comment]
Fabulous! Thank you and, yes, it's all good now :-)
