### ISSUE TITLE
PS Vita

### ISSUE THREAD

**Issue by Varon9** [XProger/OpenLara#429]
Hi! i'm experimenting a lot of crashes around the palace of midas (the more that i progress the more it crashes) it's randomly, sometimes it can happen when i die and load a save, sometimes when i open the inventory and other times just crashes while i'm running around

like here (at the end of the video, the crash screen can be seen for just a frame (the capture plugin freezes until i press the PS button)
https://youtu.be/lTLd8be78KM

Thanks so much for your work, i'm loving replaying tr1 in open lara ^^

**Comment by XProger** [comment]
yeah, PS Vita has a lot of issues, I plan to fix them in the future, when entire game will be rewritten to the "fixed" branch

**Comment by Varon9** [comment]
great to hear it, thanks so much! ^^
