### ISSUE TITLE
GBA: Crash in Lara's Manor

### ISSUE THREAD

**Issue by TsukiZero** [XProger/OpenLara#430]
![image](https://user-images.githubusercontent.com/78157224/172016579-818187b1-1a98-448b-ae88-2404e9afeadb.png)
It was all fine and dandy... Until she talked about the mess (crates) and I tried heading back to her room. The game froze then a few seconds later it produced this "windows froze" noise.

After checking with mGBA instead of the (pretty unreliable) VBACE, I noticed this doesn't happen, instead the camera changes to a "locked" position. It might be worth checking if there's some sort of error there that the mGBA glosses over while the VBACE snags there.

Couldn't find any error on mGBA's debugger that relates to the possible cause, bu did find the Gym produced a lot of "[WARN] GBA Pak Hardware:	Write to GPIO address 080000C4 on cartridge without GPIO", which consistently triggers twice when trying to jump into a wall.

**Comment by XProger** [comment]
VBA doesn't work properly with Fast Interrupts (FIQ mode of ARMv4), use mGBA
