### ISSUE TITLE
Crashes on menu on GBA SP but works fine on same flashcart with a Micro. 

### ISSUE THREAD

**Issue by P1nkz** [XProger/OpenLara#433]
I recently started using my SP after using the Micro for a while and noticed it crashes in seconds after opening the ROM, on the menu, the framerate counter goes nuts, from 1 to several thousand, music starts corrupting and then just crashes. GameBoy SP AGS-001 and EZ Flash DE. Tried setting V-Sync on and off on the Micro and saving, then loading again on SP, deleting save entirely, also tried the older Slow Cartridge version, same problem. 
Meanwhile works perfectly fine on my Micro.

**Comment by domis4** [comment]
have you tried using a different micro sd card? I've had some issues on Romhacks with my bundled chinese SD Card on my EZ Flash Omega. 

Also, whats an EZ Flash DE? never heard of that.

**Comment by P1nkz** [comment]
I haven't but I will. I recently also got a AGS-101 SP and under that it works just fine, no crash. 
Will see if the microSD changes anything, I think the SP might just be defective since the same flash cartridge with the same microSD and ROM works flawlessly with the new SP and my old Micro. 

>Also, whats an EZ Flash DE? never heard of that.
Sorry, typo. Meant EZ-Flash Omega* DE.

**Comment by domis4** [comment]
i think you can close your issue then
