### ISSUE TITLE
How to quit the program with gamepad

### ISSUE THREAD

**Issue by 25minutes** [XProger/OpenLara#434]
I'm using latest OpenLara_rpi.zip on Retropie (Raspberry Pi 3B) with 8bitdo pro 2 controller. It works fine but I cannot find a way to quit the program with gamepad. I did a quick search on Internet but couldn't find this info. I'd appreciate it if anyone can give some hints.

**Comment by XProger** [comment]
open the passport in the main menu, last page - exit game

**Comment by 25minutes** [comment]
Got it. Thank you very much!
