### ISSUE TITLE
Impossible louve 

### ISSUE THREAD

**Issue by Smallbeb** [XProger/OpenLara#445]
Hello

Congratulation for this work about TR1. This is great
I have a problem in the Scion Sanctuary Level.
![image](https://user-images.githubusercontent.com/116117617/196533249-3e9a19ac-6a5d-408f-90e2-b19db6398ee7.png)
I can not  go to the plateform. The lateral move blocked at this position.
I use Chrome to run OpenLara.

**Comment by XProger** [comment]
https://youtu.be/xvKAajLM8xc
