### ISSUE TITLE
Savegame format

### ISSUE THREAD

**Issue by contepaccio** [XProger/OpenLara#449]
I'm using TR1 for PC on OpenLara for Android on Nvidia Shield.
It works like a charm 😉
I'm trying to use TR1 savegame files, I have found a lot of that on:
https://tombraiders.net/stella/savegame/TR1saves.html 
I've tried PC, MAC, Android and PS files putting them in the game folder where is the original savegame.dat but OpenLara simply don't see any file.
Is OpenLara using a proprietary savegame format?

**Comment by XProger** [comment]
yes
