### ISSUE TITLE
Correcting level arguments while initializing game (platform/win). 

### ISSUE THREAD

**Issue by cos1110** [XProger/OpenLara#459]
https://github.com/XProger/OpenLara/blob/7a021b6edeb145372b572cddc400caaa3f3ad8a6/src/platform/win/main.cpp#LL1089C3-L1089C3

According to some testing:

```
strstr(argv[1], "--")
0x015f5f83 "--01-Caves.PHD"

strstr(argv[1], "--") == argv[1]
true

argc > 1 && strstr(argv[1], "--") == argv[1]
true

```

**Comment by XProger** [comment]
the original game doesn't have such file names

**Comment by cos1110** [comment]
I was able to overload the command line argument and load a custom level, I found somewhere. Everything runs nicely, however I had to change the boolean operator to `==` in order to load the custom level as such.
