### ISSUE TITLE
New Release on Github

### ISSUE THREAD

**Issue by ShalokShalom** [XProger/OpenLara#476]
Hi there :)

I see the last release was 2019, and the package maintainer can only rely on git builds. 
Do you plan on any future release?

Thanks

**Comment by XProger** [comment]
![image](https://github.com/XProger/OpenLara/assets/796763/135fef55-f2d1-46c6-8220-836a61864bde)

**Comment by ShalokShalom** [comment]
This does not really tell me anything that I strived to know. :)

**Comment by leahanderson1** [comment]
> This does not really tell me anything that I strived to know. :)

despite the release date being old, the actual contents of said release are automatically updated.

**Comment by ShalokShalom** [comment]
Thats not the point. Package managers from Linux distros will still ignore it. They only package, what has a recent release.

**Comment by XProger** [comment]
@ShalokShalom oh, I didn't know that OpenLara has packages already %)
