### ISSUE TITLE
3ds version doesn't seem to work with steam copy

### ISSUE THREAD

**Issue by F3arM3** [XProger/OpenLara#478]
I am trying to set up openlara on my 3ds with my steam copy so I can't follow the "copy original game cd content to 3ds/openlara file" part of the instructions but no matter how I copy it into that folder (entire game folder into openlara, renaming it to openlara, just the tombraid file, etc) openlara just keeps going back to the homebrew menu.

I don't know if I am stupid or if this really is an issue, any help would be appreciated

**Comment by XProger** [comment]
hi, use PSX files
data http://xproger.info/projects/OpenLara/files/TR1_data.7z
audio http://xproger.info/projects/OpenLara/files/TR1_audio.7z
