### ISSUE TITLE
Is it possible to play through the whole game yet?

### ISSUE THREAD

**Issue by meepingsnesroms** [XProger/OpenLara#48]
I know this is not an issue but don't know where else to ask.

**Comment by XProger** [comment]
nope

**Comment by MatthTheGeek** [comment]
Speaking of which, is there a better place to ask these kind of questions? A forum, an IRC channel, a discord? Haven't been able to find one yet.

**Comment by Lwmte** [comment]
Here is a forum: http://www.tombraiderforums.com/showthread.php?t=216618

Also there's discord chat for general TR development (OpenTomb, OpenLara, TombEditor, etc.), but I don't know how to make a link to it. @Gh0stBlade maintains it, I think he can provide the link :)

**Comment by XProger** [comment]
Also has a fb page https://www.facebook.com/OpenLaraTR/

**Comment by Gh0stBlade** [comment]
There's an issue I opened #37 which details how far each level is playable. Lots of uninterrupted features at the moment. More critically flip maps and heavy triggers prevent majority of levels from being completed.

Discord server can be accessed here: if you wish to ask non issue related questions. https://discord.gg/g329bpJ
