### ISSUE TITLE
Path Finding Error/Collision

### ISSUE THREAD

**Issue by CDrosos** [XProger/OpenLara#53]
One enemy can go inside the other:
[Look here](https://snag.gy/UehpaL.jpg)

- Here two wolfs are almost completely one inside the other.
- Also when you are on water and a bear is in the surface, the bear constantly run and attack lara, it doest walk or leave like the wolfs

**Comment by XProger** [comment]
![image](https://cloud.githubusercontent.com/assets/796763/26027767/73fea2f8-381c-11e7-8995-b7f5b900591b.png)
it's normal case for original game, but would be nice to fix it in OpenLara :)
