### ISSUE TITLE
Raw files level2 and music are missing under the Android build 

### ISSUE THREAD

**Issue by cmsanta** [XProger/OpenLara#64]
When compiling under Android I get these compilation errrors:

Error:(68, 85) error: cannot find symbol variable level2
Error:(69, 85) error: cannot find symbol variable music

Looking into it I realized that the /res/raw/ folder is missing, eg: /res/raw/level2 and /res/raw/music

Was this an oversight? Can you include the missing files?

thanks,

**Comment by XProger** [comment]
just copy LEVEL2.PSX and 05.ogg into res/raw folder and rename them as level2.jet and music.jet. It's temporary, in future versions user will have to browse a folder with original game resources.
