### ISSUE TITLE
Null pointer exceptions on Android devices with no audio support

### ISSUE THREAD

**Issue by csanta** [XProger/OpenLara#69]
The Main activity in Android is not robust enough to handle null pointers for devices with no audio support.

**Comment by XProger** [comment]
Which android device doesn't have audio support?
I'm working on OpenSL ES integration, because AudioTrack has audio latency ~300 ms

**Comment by csanta** [comment]
There's an open source version of Android that runs on Intel: https://github.com/android-ia/manifest/wiki that includes Mesa drivers for rendering, it's still under development but right now there is no support for Audio. The device I am using for testing is the Intel Joule 570x. I got Open Lara to run successfully over the weekend without audio

**Comment by XProger** [comment]
omg, thanks! %)
