### ISSUE TITLE
Bug: Lever desyncs with Lara if pulled sequentially.

### ISSUE THREAD

**Issue by Gh0stBlade** [XProger/OpenLara#79]
LEVEL2 (City of Vilcabamba) (Also possible on all other levels)
Works on: dc46426
http://i.imgur.com/s6dUbBP.jpg

Go to the switch as seen in the screenshot. Keep pressing the CTRL (Action button) After a few pulls Lara's pulling animation will desync with the switch allowing her to pass through the door before it closes. In addition, once the desync occurs Lara cannot pull the switch until the door/switch has caught back up.

**Comment by XProger** [comment]
fixed
