### ISSUE TITLE
Exception thrown on Chromium / Ubuntu 

### ISSUE THREAD

**Issue by AurelSan** [XProger/OpenLara#81]
Message received when loading the page xproger.info/projects/OpenLara : 

Uncaught TypeError : Cannot read property 'getSupportedExtensions' of undefined.

Chromium version : Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by AurelSan** [comment]
Works fine on Mozilla 53.0.2 - 64 bit though - Chromium polyfill missing ?

**Comment by XProger** [comment]
#31
