### ISSUE TITLE
Bug: Lara goes to surface for air when underwater.

### ISSUE THREAD

**Issue by Gh0stBlade** [XProger/OpenLara#87]
LEVEL7A (Cistern)
Works on: f17bd97f3ef5198b6cbdb37cb039d42d9894afb1

Location (Just to give more context of where this area is):
After obtaining the first 2 keys, open the door on the left and proceed until this point.
![image](https://user-images.githubusercontent.com/6951235/30479241-41b51910-9a0c-11e7-8ba9-987dd49529cf.png)

Issue:
![image](https://user-images.githubusercontent.com/6951235/30479517-90e0fe72-9a0d-11e7-92bb-4254d174b8dc.png)

This happens in two areas, both the same cases where the room Lara goes to the surface to get air are filled by water (due to flip map switch activation) but the room beneath it is always filled with water.

**Comment by Gh0stBlade** [comment]
![image](https://user-images.githubusercontent.com/6951235/30479738-8101a852-9a0e-11e7-821a-d3b37d158c98.png)

Probably easier to check LEVEL7B since it occurs right at the beginning of this level.

**Comment by XProger** [comment]
fixed in a89e3f8bebc9c142e9bc0aa5daa5cb1c671f8422
