### ISSUE TITLE
WebGL World not loading on windows 7

### ISSUE THREAD

**Issue by TheIndra55** [XProger/OpenLara#99]
Looks like the world isn't loading on in chrome on Windows 7
![image](https://user-images.githubusercontent.com/15322107/33881806-42ad3374-df36-11e7-9407-b1ac9cbb78a3.png)

**Comment by XProger** [comment]
@TheIndra55 can you scroll up to shader compilation errors?

**Comment by TheIndra55** [comment]
Sorry for the delay i'll send you that information tommorow!

**Comment by TheIndra55** [comment]
Sorry for the delay
![image](https://user-images.githubusercontent.com/15322107/34196713-9d4ee236-e563-11e7-85f3-b6ef2d39b4cb.png)

**Comment by XProger** [comment]
thanks, I'll fix it soon

**Comment by XProger** [comment]
@TheIndra55 try it now.

**Comment by TheIndra55** [comment]
fixed, thanks !
